### ISSUE TITLE
Unrecognized field "schemaLocation"

### ISSUE THREAD

**Issue by kokorin** [qoomon/maven-git-versioning-extension#102]
Hello!
First of all great extension, thank you!

I want to use it my project so I followed the instruction. It seems `schemaLocation` can't be parsed by maven itself or maven-git-versioning-extension. If I remove `schemaLocation` attribute from maven-git-versioning-extension.xml  the extension works.

Please check this sample project showing the problem [maven-git-versioning-extension-bug.zip](https://github.com/qoomon/maven-git-versioning-extension/files/6234121/maven-git-versioning-extension-bug.zip)

Maven error
>./mvnw
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=1024M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=4048M; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] 
[INFO] --- me.qoomon:maven-git-versioning-extension:6.4.0 [core extension] ----
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /home/user/projects/maven-git-versioning-extension-bug/pom.xml: Unrecognized field "schemaLocation" (class me.qoomon.maven.gitversioning.Configuration), not marked as ignorable (6 known properties: "branch", "updatePom", "commit", "disable", "preferTags", "tag"])
 at [Source: (File); line: 2, column: 174] (through reference chain: me.qoomon.maven.gitversioning.Configuration["schemaLocation"]) @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/user/projects/maven-git-versioning-extension-bug/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/user/projects/maven-git-versioning-extension-bug/pom.xml: Unrecognized field "schemaLocation" (class me.qoomon.maven.gitversioning.Configuration), not marked as ignorable (6 known properties: "branch", "updatePom", "commit", "disable", "preferTags", "tag"])
[ERROR]      at [Source: (File); line: 2, column: 174] (through reference chain: me.qoomon.maven.gitversioning.Configuration["schemaLocation"])
[ERROR]     -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnrecognizedPropertyException

Maven wrapper version just in case
> ./mvnw -v
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=1024M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=4048M; support was removed in 8.0
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/user/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 1.8.0_275, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-70-generic", arch: "amd64", family: "unix"

Please, let me know if you need more information.

**Comment by qoomon** [comment]
Thank you for reporting. I'll have a look

**Comment by qoomon** [comment]
should be fixed in version `6.4.1`

**Comment by kokorin** [comment]
Confirmed: fixed, thank you!

**Comment by qoomon** [comment]
thx for confirming.
