### ISSUE TITLE
Cannot set custom versionFormat for specific branch

### ISSUE THREAD

**Issue by Dizzymon** [qoomon/maven-git-versioning-extension#12]
Hello, I am trying to have a custom branch (alongside master) without the branch name. But whenever I build the Jenkins job, the branch name is displayed for all branches. This is how the config xml looks like:
```
<configuration>
    <branches>
        <branch>
            <pattern>develop</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
		<branch>
            <pattern>master</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
		<branch>
            <pattern>custom_branch</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
        <branch>
             <pattern>release/.*</pattern>
             <prefix>release/</prefix>
             <versionFormat>${branch}${version.release}-SNAPSHOT</versionFormat>
         </branch>
    </branches>
</configuration>
```

**Comment by qoomon** [comment]
I'll investigate

**Comment by qoomon** [comment]
can you provide me a branch name example and the maven command you execute?

**Comment by Dizzymon** [comment]
Sure. The branch name is in the format GHFH_23423_tests_VB and the Maven command I inserted in Jenkins is -Dproject.branch=${BRANCH}.

**Comment by qoomon** [comment]
and your config looks like this ?
```xml
<configuration>
    <branches>
        <branch>
            <pattern>develop</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
		<branch>
            <pattern>master</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
	<branch>
            <pattern> GHFH_23423_tests_VB </pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
        <branch>
             <pattern>release/.*</pattern>
             <prefix>release/</prefix>
             <versionFormat>${branch}${version.release}-SNAPSHOT</versionFormat>
         </branch>
    </branches>
</configuration>
```

**Comment by qoomon** [comment]
or can you post the real content of maven-git-versioning-extension.xml

**Comment by qoomon** [comment]
Can you checkout what the value of ${BRANCH} actually is

**Comment by qoomon** [comment]
if you make use of this [jenkins git plugin](https://wiki.jenkins.io/display/JENKINS/Git+Plugin) 
then you should call maven like this  `mvn verify -Dproject.branch=${GIT_BRANCH#*/}`
`${GIT_BRANCH#*/}` will remove leading 'origin/' prefix from `${GIT_BRANCH}`

**Comment by Dizzymon** [comment]
That is exactly how the xml file looks like. I only replaced the branch value, but the branch format is the same. The value of ${BRANCH} is origin/GHFH-23423_tests_VB. I will  try the Maven command, thank you.

**Comment by Dizzymon** [comment]
![screenshot_29](https://user-images.githubusercontent.com/33157774/43569292-aec01dea-963f-11e8-89d1-42ef8917ad27.png)
This is how my Maven commands look like, but I still get origin/ displayed as well. What I found odd is that even if I don't mention any branch command in Goals and options, the branch will still be displayed next to my Snapshot version.

**Comment by qoomon** [comment]
Ok that's the problem my extension expecst to get the branch name only without origin/ prefix
Unfortunately I am not using Jenkins currently, could you try to use $GIT_LOCAL_BRANCH variable, regarding to fit plugin docs it should contains only the branch name.

**Comment by qoomon** [comment]
And please try `-Dproject.branch=$(echo ${GIT_BRANCH} | sed 's|^origin/||')` as well

**Comment by qoomon** [comment]
and you may need to surround  ${GIT_BRANCH} and ${GIT_LOCAL_BRANCH} with quotes like "${GIT_BRANCH}"

**Comment by qoomon** [comment]
to test what value is set to `-Dproject.branch`
please run following examples and provide me the output
`mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH}" -q` 
expected result `origin/GHFH-23423_tests_VB`
`mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_LOCAL_BRANCH}" -q`
expected result `GHFH-23423_tests_VB`
`mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH#*/}" -q`
expected result `GHFH-23423_tests_VB`

**Comment by Dizzymon** [comment]
It seems the issues were caused by us using an older version of Maven. I am in the process of adapting everything to the newer Maven version and will return here and post an update regarding the functionality of the extension.

**Comment by qoomon** [comment]
Okay, please contact me if you need any help.

**Comment by Dizzymon** [comment]
Hello! The Maven extension now works perfectly for me on my local machine, but not on Jenkins. Jenkins ignores the maven-git-versioning-extension file and just simply replaces the ${branch} parameter in the pom file with the branch I tell Jenkins to build. This can be noticed because on Jenkins the pom file version is not affected by any changes I make in the maven-git-versioning-extension file, but changes I make locally in this file work correctly. Do you have maybe some insight into this issue?

**Comment by qoomon** [comment]
How the command line of maven extension looks like?

**Comment by qoomon** [comment]
to test what value is set to -Dproject.branch
please run following examples and provide me the output
mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH}" -q
expected result origin/GHFH-23423_tests_VB
mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_LOCAL_BRANCH}" -q
expected result GHFH-23423_tests_VB
mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH#*/}" -q
expected result GHFH-23423_tests_VB

**Comment by GabrielCiordas** [comment]
Hi,

```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH}" -q```
returns no output
```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_LOCAL_BRANCH}" -q```
returns no output
```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH#*/}" -q```
returns no output

I'm using Maven v3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)

Thanks

**Comment by GabrielCiordas** [comment]
Hi,

In Jenkins:
```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH}" -q```
returns: ```origin/develop```
```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_LOCAL_BRANCH}" -q```
returns no ooutput
```mvn exec:exec -Dexec.executable='echo' -Dexec.args="${GIT_BRANCH#*/}" -q```
returns: ```develop```

Thanks

**Comment by qoomon** [comment]
well then you have to exectute then maven command in the following way and it should work like on your machine. replace `clean` goal with what ever you need 
`maven clean -Dproject.branch="${GIT_BRANCH#*/}"`

**Comment by qoomon** [comment]
Hi, I'll have look at it today. It should set the project.version, actually 😀

**Comment by GabrielCiordas** [comment]
Hi again,

I just figured out that the problem is most likely on our jenkins machine (unix based). 
For some reason, our maven-git-versioning-extension is fired off during build process at all, while it runs perfectly on my local Windows 10 machine.

**Comment by GabrielCiordas** [comment]
Thanks for your help, I figured out the problem and we are most likely going to continue using your extension.

**Comment by pduchesne** [comment]
@GabrielCiordas can you document what your problem was? We're hitting a similar problem (extension not firing at all in jenkins).

**Comment by GabrielCiordas** [comment]
@pduchesne its becuase theres a bug in jenkins maven plugin where it doesnt recognize folders/files that have  . In front of the name. I switched the job out to a freestyle one. I dont have a link to the bug itself cuz im on my phone, but its known.

**Comment by GabrielCiordas** [comment]
You need to make sure the build executor can find your files, i debugged by executing ls in the root where i checked out my code and thats how i found out about the bug.
