### ISSUE TITLE
Question Maven Multiple Modules Project

### ISSUE THREAD

**Issue by kule1015** [qoomon/maven-git-versioning-extension#122]
Hi,

i have a question regarding a maven multi module project and the extension.

I have this basic project structure.

```log
INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] test-root                                                          [pom]
[INFO] adapter                                                            [pom]
[INFO] client                                                             [pom]
```

When I am building the root project everything works fine. But if I build a child module without explicit providing `<version>`,
maven resolves the template string of the root project as version ('GENERATED'). 

```xml
  <parent>
    <artifactId>test-root</artifactId>
    <groupId>org.acme</groupId>
    <version>${revision}</version>
  </parent>

  <groupId>org.acme.client</groupId>
  <artifactId>client</artifactId>
  <!-- <version>${revision}</version> -->
  <packaging>pom</packaging>
```

```log
[INFO] --- me.qoomon:maven-git-versioning-extension:6.4.4 [core extension] ----
[INFO] git ref: master (branch)
[INFO] 
[INFO] org.acme.client:client
[INFO] project version: ${revision}
[INFO] 
[INFO] 
[INFO] -----------------------< org.acme.client:client >-----------------------
[INFO] Building client GENERATED
[INFO] --------------------------------[ pom ]---------------------------------
```

When uncomment the `version` tag everything works fine again.

```log
[INFO] --- me.qoomon:maven-git-versioning-extension:6.4.4 [core extension] ----
[INFO] git ref: master (branch)
[INFO] 
[INFO] org.acme.client:client
[INFO] project version: master-SNAPSHOT
[INFO] 
[INFO] 
[INFO] -----------------------< org.acme.client:client >-----------------------
[INFO] Building client master-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
```

Is there a way to build child components without providing the duplicate `<version>` information?

Thanks in advance !

**Comment by qoomon** [comment]
it's always a little tricky if you build child project from module folder. Anyway may you provide a tiny sample project so I can reproduce your behaviour on my machine?

**Comment by kule1015** [comment]
Hi, this is the project.
After building the root project, try to build the client module. If you comment '<version>' in the child pom (s.above) the template string of the root project will be used.

[test-root.zip](https://github.com/qoomon/maven-git-versioning-extension/files/6723990/test-root.zip)

**Comment by qoomon** [comment]
I'll have look

**Comment by qoomon** [comment]
Okay I got your point. Currently this behaviour is expected, because this extension only changes existing pom fields (xml tags)
However I consider to change it. I'll keep you posted.

**Comment by qoomon** [comment]
Oh actually there was bug as well :-)

**Comment by kule1015** [comment]
Thanks for the quick response!

**Comment by qoomon** [comment]
I fixed it. I'll do a release. Stay tuned.

**Comment by qoomon** [comment]
version `6.4.6` is released. may you confirm it works?

**Comment by kule1015** [comment]
I can confirm that it works. Thank you very much 👍
