### ISSUE TITLE
Question Possibility Set Revision Property

### ISSUE THREAD

**Issue by kule1015** [qoomon/maven-git-versioning-extension#123]
Hi,
I have a question about a possible feature. 

Is there the possibility that the extension can set the `<revision>` property? Besides the current state where the `<version>` tag is set.

**Comment by qoomon** [comment]
I think it is possible, could you explain your scenario a little bit more in detail?

**Comment by kule1015** [comment]
It would give the possibility to use the extension and the flatten plugin [Flatten Plugin](https://www.mojohaus.org/flatten-maven-plugin/). Because the extension will override `<version>` which break some linkages of the flatten plugin.

**Comment by qoomon** [comment]
Could you provide a simple example project with the wrong behavior and the expected result?

**Comment by qoomon** [comment]
If you don't want the version to change just set `<versionFormat>${version}</versionFormat>`

**Comment by qoomon** [comment]
to update revision property you could use following config
```xml
<property>
    <name>revision</name>
    <valueFormat>${branch}-SNAPSHOT</valueFormat>
</property>
```

**Comment by qoomon** [comment]
@kule1015 **Complete Branch Config Example**
```xml
<branch>
        <pattern>feature/.*</pattern>
        <versionFormat>${version}</versionFormat>
        <property>
                 <name>revision</name>
                 <valueFormat>${branch}-SNAPSHOT</valueFormat>
        </property>
</branch>
```

**Comment by kule1015** [comment]
Sorry for the late response. Thanks!
