### ISSUE TITLE
Jenkins multi-branch-pipeline is giving commit versions instead of branch versions

### ISSUE THREAD

**Issue by sterfpaul** [qoomon/maven-git-versioning-extension#15]
Steps to reproduce: 
Create project with a Jenkinsfile
Create a multi branch pipeline in Jenkins.
Create a branch called: feature/test-branch
Use the following config:
```xml
<configuration>
    <branches>
        <branch>
            <pattern>master</pattern>
            <versionFormat>${version.release}</versionFormat>
        </branch>
        <branch>
            <pattern>feature/.*</pattern>
            <prefix>feature/</prefix>
            <versionFormat>${branch}-SNAPSHOT</versionFormat>
        </branch>
    </branches>
    <tags>
        <tag>
            <pattern>version/.*</pattern>
            <prefix>version/</prefix>
            <versionFormat>${tag}</versionFormat>
        </tag>
    </tags>
</configuration>
```

Expected result:
See test-branch-SNAPSHOT as the version.

Actual results
[INFO] --- maven-git-versioning-extension:3.0.2 ---
[INFO] backend:1.0.2-SNAPSHOT - commit: bc4edda51ebe991aeb7a210e7ec606973d02c8c9 -> version: bc4edda51ebe991aeb7a210e7ec606973d02c8c9

**Comment by qoomon** [comment]
Hi, did you provide branch name as described here [jenkins-setup](https://github.com/qoomon/maven-git-versioning-extension#jenkins-setup)?

please execute following command within your jenkins job
`MAVEN_PROJECT_BRANCH=${GIT_BRANCH#origin/} mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q`
or
`mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q -Dproject.branch=${GIT_BRANCH#origin/}`

**Comment by qoomon** [comment]
No problem, glad I could help.
