### ISSUE TITLE
Can this extension be used to dynamically set `group` and `artifactId`?

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#154]
We are using this plugin in all of our projects to dynamically set `version` based on git branch/tag. We had a small use case arise where it would be nice to also set `group` and `artifactId` at build time. Is this possible with the current version of the extension?

We tried using normal property syntax and providing values at the command line (see https://stackoverflow.com/a/67583847/1880761), but Maven logs warnings so it didn't seem like the most desirable approach.

Thoughts? Thanks!

**Comment by qoomon** [comment]
It should be possible by using the property manipulation feature of this extension, so you don't need to pass properties on the command line. However the warnings will still be shown.

**Comment by l3ender** [comment]
This approach would still require configuring the original pom to reference the properties for `group` and `artifactId`, correct (e.g. `<groupId>${maven_group_id}</groupId>`). And to confirm, `updatePom` would not persist those values?

I'm sure it's a rare use case, but what I'm trying to solve is having a generic shell of a project which someone can use to generate an artifact based on a few other values they provide at runtime. They would provide all Maven coordinates when generating. I can accomplish what is needed with `version`, but not `group` and `artifactId`.

Thoughts?

**Comment by qoomon** [comment]
> This approach would still require configuring the original pom to reference the properties for group and artifactId, correct? e.g. <groupId>${maven_group_id}</groupId>. And to confirm, updatePom would not persist those values?

yes and yes

>I'm sure it's a rare use case, but what I'm trying to solve is having a generic shell of a project which someone can use to generate an artifact based on a few other values they provide at runtime. They would provide all Maven coordinates when generating. I can accomplish what is needed with version, but not group and artifactId.

have you tried using maven archetypes?

**Comment by l3ender** [comment]
I don't think archetype will get us exactly what we want, but I will check more into it. Thanks for the information!
