### ISSUE TITLE
Support multiple types of configurations

### ISSUE THREAD

**Issue by johanblumenberg** [qoomon/maven-git-versioning-extension#157]
## Description

In a multimodule project, there might be multiple types of modules that require different types of versioning.

For example, a project might contain API jar files and a number of war files to be deployed.

The API jar files are published to a public maven repository and require semantic versioning based on tags.
The war files should only be versioned by an increasing number.

This could be achieved by adding multiple types of configuation for different pojects, for example like this:

```xml
<configuration xmlns="https://github.com/qoomon/maven-git-versioning-extension"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://github.com/qoomon/maven-git-versioning-extension https://qoomon.github.io/maven-git-versioning-extension/configuration-7.0.0.xsd">

    <projects>
        <project>
            <groupId>my.company.api</groupId>

            <refs>
                <ref type="tag">
                    <pattern><![CDATA[v(?<version>.*)]]></pattern>
                    <version>${ref.version}${dirty.snapshot}</version>
                </ref>
            </refs>
        </project>

        <project>
            <groupId>my.company.microservices</groupId>

            <refs>
                <ref type="branch">
                    <pattern>master</pattern>
                    <version>1.0.${describe.distance}</version>
                </ref>
            </refs>
        </project>
    </projects>

    <rev>
        <version>1.0.0-SNAPSHOT</version>
    </rev>
</configuration>
```

If a project matches any of the configured projects, that configuration will be used. If it doesn't match any of the configured projects, it will use the global configuration just as before.
A poject section in this example is matched on `groupId`, but it could also be matched by `artifactId` or both.

**Comment by qoomon** [comment]
In general I think it is a bad practice to have different versions of artefacts within one repository.

I need to think about that.

**Comment by johanblumenberg** [comment]
> In general I think it is a bad practice to have different versions of artefacts within one repository.

In general I would agree, especially if you are developing a library.

However, when you work on a poduct where part of it is going directly to production and part of it is an API used by customers, I think it makes sense to separate the versioning. I don't want to step the version of the API that my customers see every time I deploy a new version of the backend.

The the other option would be to split the code into multiple repositories, one for each API that I'm publishing (for app developers, backend integrations), and one for the deployable product itself. That would mean quite a lot of extra complexity to keep all the versions in sync and to make changes across repositories.

**Comment by qoomon** [comment]
I had the same discussion in my team, but we agreed that server and client artefacts have totally separate life and version cycles and therefore should not be within the same repo. 

Problematic Scenarios:
* A breaking change in the client is not necessarily a breaking change in the server api 
* There is no support in GitHub GitLab or others to manage artefact based git version tags

**Comment by johanblumenberg** [comment]
> * A breaking change in the client is not necessarily a breaking change in the server api

yes, so this is why you need to have separate versioning of diffeent artifacts

> * There is no support in GitHub GitLab or others to manage artefact based git version tags

The way I have always done it is to tag each release using different tags, for example `client-api-v1.5.0`.
