### ISSUE TITLE
Adding snapshot on distance

### ISSUE THREAD

**Issue by mibollma** [qoomon/maven-git-versioning-extension#158]
Background: I'm using [anothrNick/github-tag-action](https://github.com/anothrNick/github-tag-action) to automatically add a semver tag to every commit on the main branch for continuous deployment.

I would find it useful to have a ${describe.distance.snapshot} variable similar to ${dirty.snapshot} which resolves to -SNAPSHOT if distance is nonzero and resolves to empty string if distance is zero.
This way all untagged commits receive a snapshot suffix and all tagged commits on the main branch are built without snapshot suffix.

Any opinions on that?

**Comment by qoomon** [comment]
> This way all untagged commits receive a snapshot suffix and all tagged commits on the main branch are built without snapshot suffix.

This is already possible by having a branch and a tag config see example config below
```xml
<configuration xmlns="https://github.com/qoomon/maven-git-versioning-extension"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://github.com/qoomon/maven-git-versioning-extension https://qoomon.github.io/maven-git-versioning-extension/configuration-7.0.0.xsd">

    <refs considerTagsOnBranches="true">
      
        <ref type="tag">
            <pattern><![CDATA[v(?<version>.*)]]></pattern>
            <version>${ref.version}</version>
        </ref>

        <ref type="branch">
            <pattern>.+</pattern>
            <version>${ref}-SNAPSHOT</version>
        </ref>

    </refs>

</configuration>
```

**Comment by mibollma** [comment]
You are right. Thanks for clarifying.
