### ISSUE TITLE
How to make use of <properties>?

### ISSUE THREAD

**Issue by aberrant80** [qoomon/maven-git-versioning-extension#174]
Hi, I'm currently exploring this extension (thanks for creating it), but I found myself a bit confused about the use of `<properties>`.

In the ReadMe, the example configuration is given like so:

          <ref type="branch">
            <pattern>.+</pattern>
            <version>${ref}-SNAPSHOT</version>
            <properties>
                <foo>${ref}</foo>
            </properties>
        </ref>

What exactly is the purpose of "foo" here? How can I make use of these `<properties>`?

**Comment by qoomon** [comment]
Hi, basically you can adjust/overwrite property values the same way you configure `<version>`.
`foo` is just a dummy property name, it could be any property name of your project pom.xml.
Does that explanation help?

**Comment by aberrant80** [comment]
Am I correct to assume that `<properties>` is only used for when <updatePom> is "true"?

I'm actually exploring how Jenkins can override these config. For example, to use the tag version by default, but allow for an override. For example, say I configure something like this:

      <ref type="branch">
          <pattern><![CDATA[release/(?<version>.+)]]></pattern>
          <describeTagPattern><![CDATA[(?<version>.*)]]></describeTagPattern>
          <version>${describe.tag.version}-SNAPSHOT</version>
      </ref>

Is there any way such that I can make Jenkins build it as a different version instead (by passing in a build parameter, for example)?

**Comment by qoomon** [comment]
Yes you can, see https://github.com/qoomon/maven-git-versioning-extension#format-placeholders
e.g. `${env.BUILD_NUMBER:-local}`

**Comment by aberrant80** [comment]
Oh, I saw that. I guess I'm more looking for something like this: `<version>${property.override:${version}}</version>`

**Comment by qoomon** [comment]
I would recommend using environment variables for your use-case

**Comment by aberrant80** [comment]
Ah, gotcha. Thanks.
