### ISSUE TITLE
relatedProjects doesn't work

### ISSUE THREAD

**Issue by barambuk** [qoomon/maven-git-versioning-extension#184]
First of all, thank you for amazing plugin!

I have 2 projects: library and application. Library appears as a dependency in "dependencies" section of app's pom. I created "my-feature-branch" in library and app projects as well. I put library project as a related project in maven-git-versioning-extension.xml of app.
```
    <relatedProjects>
        <project>
            <groupId>com.example</groupId>
            <artifactId>library</artifactId>
            <version>1.0-SNAPSHOT</version>
        </project>
    </relatedProjects>
```

Action: "mvn install" of library and app projects

Expected behavior: when I use "mvn install" of app project, it will change the version of library from "1.0-SNAPSHOT" to "my-feature-branch-SNAPSHOT" because the relatedProjects feature
Actual behavior: the version of library in app's pom is still my-feature-branch

**Comment by barambuk** [comment]
Yes, sure
[dependency.zip](https://github.com/qoomon/maven-git-versioning-extension/files/8377198/dependency.zip)

**Comment by javiercj93** [comment]
Is there any update on this? I am also facing this issue

**Comment by qoomon** [comment]
Sorry for the delay, I'll work on it tomorrow.

**Comment by qoomon** [comment]
I am able to reproduce the error, I'll keep you posted

**Comment by qoomon** [comment]
@barambuk you use version ´7.1.2´ in you example project. You need to use the latest version ´7.3.0´, then its working as expected.

**Comment by qoomon** [comment]
@javiercj93 which version do you use?

**Comment by qoomon** [comment]
I'll close this issue for now. please reopen it, if you still facing the issue.
