### ISSUE TITLE
Incorrect version in a multimodule project with enforce plugin

### ISSUE THREAD

**Issue by OneHalf3544** [qoomon/maven-git-versioning-extension#19]
I have a problem with maven-git-versioning-extension. Enforcer plugin fails the build during checking a version compatibility.

Example of a project:
https://github.com/OneHalf3544/mgvp-bug-example/tree/feature/TICKET-123/description

pom.virtual.xml files contain a correct version, but Enforcer plugin shows the error:
```
Dependency convergence error for mgve-example:printer:1.0.0-TICKET-123-description-TICKET-123-description-SNAPSHOT paths to dependency are:
+-mgve-example:world-greater:1.0.0-TICKET-123-description-SNAPSHOT
  +-mgve-example:greater:1.0.0-TICKET-123-description-SNAPSHOT
    +-mgve-example:printer:1.0.0-TICKET-123-description-TICKET-123-description-SNAPSHOT
and
+-mgve-example:world-greater:1.0.0-TICKET-123-description-SNAPSHOT
  +-mgve-example:printer:1.0.0-TICKET-123-description-SNAPSHOT
```

**Comment by qoomon** [comment]
Hi, thx for reporting this behaviour i will investigate on this at this weekend.

**Comment by qoomon** [comment]
Fixed it in release v3.1.1

**Comment by qoomon** [comment]
Could you confirm the fix is working for you?

**Comment by OneHalf3544** [comment]
Yeah, it's working in my real project. Thank you!
