### ISSUE TITLE
Add option to set snapshot version based on prior tag

### ISSUE THREAD

**Issue by tylerbenson** [qoomon/maven-git-versioning-extension#191]
Consider the semantics for this gradle plugin with similar goals:
https://github.com/allegro/axion-release-plugin

I would like the ability to configure this plugin to follow that versioning style.

Specifically, if I have a tag of version `1.0.0` then the next commit added after the tag would result in a version of `1.0.1-SNAPSHOT`.  This provides more consistent version numbering and better indication of what the next version number might be.

Thanks!  Overall nice extension with decent documentation.

**Comment by qoomon** [comment]
Hi @tylerbenson currently there is no support for a placeholder for next patch version based on last tag. Do you have some ideas how to call this placeholder and how to determine patch version in an tag name in a generic way?

**Comment by qoomon** [comment]
I think the easiest way would be to have a version pattern like 
```xml
<ref type="branch">
    <pattern>.+</pattern>
    <describeTagPattern>v(.+)</describeTagPattern>
    <version>${describe.tag.1}-NEXT-SNAPSHOT</version>
</ref>
```

**Comment by tylerbenson** [comment]
Another option:
`<version>${version.major}.${version.minor}.${version.patch.next}-SNAPSHOT</version>`

Where `.next` would take whatever the current number is and increment it.

**Comment by qoomon** [comment]
version.patch is the static project version, so this won't work

**Comment by tylerbenson** [comment]
What about something like
`${describe.tag.nextPatch}` or `${describe.tag.major}.${describe.tag.minor}.${describe.tag.patch.next}?

**Comment by qoomon** [comment]
I think I'll go for
```
${describe.tag.major}
${describe.tag.minor}
${describe.tag.patch}
${describe.tag.major.next}
${describe.tag.minor.next}
${describe.tag.patch.next}
```

**Comment by qoomon** [comment]
I'll add following placeholders in version 6.0.0
  - `${describe.tag.version}`
  - `${describe.tag.version.major}`
  - `${describe.tag.version.major.next}`
  - `${describe.tag.version.minor}`
  - `${describe.tag.version.minor.next}`
  - `${describe.tag.version.path}`
  - `${describe.tag.version.patch.next}`

**Comment by qoomon** [comment]
feel free to try version `8.0.0`

**Comment by tylerbenson** [comment]
Seemed to work well.  Thanks!

**Comment by tylerbenson** [comment]
Hmm... Seems to have issue in GitHub:
```
java.lang.IllegalStateException: couldn't find matching tag in shallow git repository
```

Is this expected?

**Comment by qoomon** [comment]
@tylerbenson most CI/CD pipelines checkout with a depth of 1, that means there is no history by default. You need to increase the depth to reasonable value or just do a full clone.
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags.

from https://github.com/actions/checkout

**Comment by tylerbenson** [comment]
Awesome.  Adding the history fixed it (it's a small repo so I did all).  Thanks for explaining that.

**Comment by qoomon** [comment]
Glad to hear that.
