### ISSUE TITLE
Prefix isn't removed since 3.1.1

### ISSUE THREAD

**Issue by jerchende** [qoomon/maven-git-versioning-extension#20]
Since version 3.1.1 the prefix isn't removed from the version tag...

Using this config:
```
<configuration>
  <branches/>
  <tags>
    <tag>
      <pattern>v.*</pattern>
      <prefix>v</prefix>
      <versionFormat>${tag}</versionFormat>
    </tag>
  </tags>
</configuration>
```

I expect when building a git tag "v1.6.2" a version 1.6.2 to be build, but it is v1.6.2

**Comment by qoomon** [comment]
Fixed it in version 3.2.1 should be available on [maven central](https://search.maven.org/search?q=g:me.qoomon%20AND%20a:maven-git-versioning-extension) in some minutes.
