### ISSUE TITLE
Limit final version length

### ISSUE THREAD

**Issue by NewLunarFire** [qoomon/maven-git-versioning-extension#204]
Hi,

I've encountered an issue this morning while integrating the extension into our CI. We use Bamboo as our CI and Sonar for static analysis. We had a 92 character branch name, which after applying to my pattern (0-${ref}-SNAPSHOT), came to be 102 characters. And Sonar threw up this error: 

`build 22-Jun-2022 11:33:02 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project istar-nextgen-c2s-radar-parent-project: "0-feature-...-SNAPSHOT" is not a valid project version. The maximum length is 100 characters. -> [Help 1]`

Is it possible to add a length limit to the resulting version? Either by specifying a limit on part of a pattern or the resulting string?

**Comment by qoomon** [comment]
if you really want that behaviour you could use a regex for that e.g.
```xml
<ref type="branch">
    <pattern><![CDATA[(?<limited>.{1,90}).*]]></pattern>
    <version>${ref.limited}-SNAPSHOT</version>
</ref>
```

**Comment by NewLunarFire** [comment]
I got to test this and it works really well, thank you for your help.
