### ISSUE TITLE
Required Java version not clear

### ISSUE THREAD

**Issue by limelier** [qoomon/maven-git-versioning-extension#208]
Hello,

This isn't really a bug or a problem, but it took me a very long time to figure out that versions past 7.4.0 are not compatible with Java 8, and that's why they weren't doing anything. It would be cool if this was clarified somewhere in the README.

**Comment by qoomon** [comment]
I've added following entry to README
* ⚠️ minimal required java version is `11`

**Comment by HiGein** [comment]
Thank you very much for raising this issue. This saved me a lot of time to understand why the extensions doesn't work on the project. I was able to use 7.4.0 successfully.
