### ISSUE TITLE
Wrong regex anchor in removePrefix

### ISSUE THREAD

**Issue by wheene** [qoomon/maven-git-versioning-extension#21]
Hi, your library works great for me but I've hit one problem recently.
I need to use the `<prefix>` in branch configuration but it does not affect the final version.
I have tracked the problem down to `StringUtil#removePrefix` - there is wrong regex anchor which makes the match never pass and prefix is never removed. I already have a patch which fixes the issue for me locally:
``` diff
     public static String removePrefix(String string, String prefix) {
 
         String prefixRegex = prefix;
-        if(!prefix.startsWith("$")){
-            prefixRegex = "$" + Pattern.quote(prefix);
+        if(!prefix.startsWith("^")){
+            prefixRegex = "^" + Pattern.quote(prefix);
         }
 
         return string.replaceFirst(prefixRegex, "");
```
And a test (which fails on current master) showing this indeed works:
``` diff
+package me.qoomon.maven.extension.gitversioning;
+
+import static org.junit.Assert.assertEquals;
+import org.junit.Test;
+
+public class StringUtilTest {
+
+    @Test
+    public void removesPrefixRemovesPatternFromStartOfWord() throws Exception{
+        assertEquals("RestOfText", StringUtil.removePrefix("somePrefixRestOfText", "somePrefix"));
+    }
+
+    @Test
+    public void removePrefixLeavesPatternInsideWord() throws Exception{
+        assertEquals("someTextWithPatternInMiddle", StringUtil.removePrefix("someTextWithPatternInMiddle", "Pattern"));
+        assertEquals("someTextEndingWithPattern", StringUtil.removePrefix("someTextEndingWithPattern", "Pattern"));
+    }
+}
```
I'd be more than happy to submit a PR but have found no contributing section, what is your policy?
It would be great if this fix could get added and appear in maven central.

Cheers

**Comment by qoomon** [comment]
I fixed in version 3.2.2 should be available at maven central in some minutes.

**Comment by wheene** [comment]
Hey thanks for the quick reaction. Seems small typo still slipped in, I have created PR #22 with fix.

**Comment by qoomon** [comment]
thank you so much, sorry for the hassle I was in a hurry :-D.
I will release a new version in a couple of minutes.

**Comment by qoomon** [comment]
version 3.3.0 is released, just wait some minutes to be available on central

**Comment by wheene** [comment]
Thanks :)
