### ISSUE TITLE
Extend GitLab CI support for merge request pipelines

### ISSUE THREAD

**Issue by a-grasso** [qoomon/maven-git-versioning-extension#217]
As is, the maven plugin does not solve the git situation correctly when used inside gitlab merge request pipelines.

Reasoning lies within that already supported environment variables CI_COMMIT_BRANCH and CI_COMMIT_TAG are not present in gitlab merge request pipelines. 

Therefore, the gitlab merge request pipeline specific environment variable CI_MERGE_REQUEST_SOURCE_BRANCH_NAME must be added when handling the git situation for gitlab ci.

**Comment by qoomon** [comment]
feel free to try version `9.3.1`

**Comment by a-grasso** [comment]
The change was tested as of in v7.4.0, worked as it should ;)
