### ISSUE TITLE
Tag 'projectVersionPattern' not in highest available XSD (7.0.0)

### ISSUE THREAD

**Issue by JWT007** [qoomon/maven-git-versioning-extension#220]
The "`<projectVersionPattern>`" tag is not defined in the 7.0.0 XSD.

Please provide a more current XSD matching the current release version.

**Comment by qoomon** [comment]
flee free to try https://github.com/qoomon/maven-git-versioning-extension/blob/master/docs/configuration-9.1.0.xsd

**Comment by JWT007** [comment]
Thank you! :) at first glance seems good 💯
