### ISSUE TITLE
v9.3.2 does not remove the `v` from `${describe.tag.version}`

### ISSUE THREAD

**Issue by vincejv** [qoomon/maven-git-versioning-extension#221]
Hi it seems like v9.3.2 broke something in `${describe.tag.version}`

My git tags are formatted like

- v1.0.0
- v1.0.1

on v9.3.1 `${describe.tag.version}` would output the following for the corresponding tags above

- 1.0.0
- 1.0.1

on v9.3.2 `${describe.tag.version}` would output the following instead (doesn't remove the `v`'s)

- v1.0.0
- v1.0.1

Before, maven git versioning extension would automatically remove the `v` from the tag so the resulting `${describe.tag.version}` would strip out the `v`. This functionality is broken on v9.3.2 and the output retains the letter `v`, can you please help to check?

**Comment by qoomon** [comment]
should be fixed in version `9.3.3`
