### ISSUE TITLE
Allow combined overwrite and default value for properties

### ISSUE THREAD

**Issue by theit** [qoomon/maven-git-versioning-extension#232]
Hi,

actually there are options for either overwriting a property if a value exists or specify a default value if a property does not exist. What about combining this?

I.e. something such as `${name:+foo:-bar}` to answer `foo` if `${name}` exists and `bar` if `${name}` is undefined?

This way you could use the following configuration:

```xml
<configuration
        xmlns="https://github.com/qoomon/maven-git-versioning-extension"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/qoomon/maven-git-versioning-extension https://qoomon.github.io/maven-git-versioning-extension/configuration-9.4.0.xsd">
        <rev>
                <version>${describe.tag}${describe.distance:+-:-}${describe.distance:-}${dirty:+-dirty}</version>
        </rev>
</configuration>
```
to let the plugin calculate a version number similar to what `git describe --tags --always --dirty` returns?

**Comment by qoomon** [comment]
Sounds interesting however I don't get your use case.
