### ISSUE TITLE
Support overwriting properties defined in parent

### ISSUE THREAD

**Issue by frelibert** [qoomon/maven-git-versioning-extension#235]
Current implementation supports overwriting properties that are defined in the pom itself (under the root or in profiles).
If you want to overwrite a property that is defined in a parent of the pom, you first need to define that property itself again in the pom otherwise it doesn't get picked up. That means you need to alter the source of the pom and that is not what we want to do.

It would be better if properties, defined in the extension's configuration, get added if they are not yet in the pom so they can overwrite parent properties.

**Comment by qoomon** [comment]
released in version `9.6.1`
