### ISSUE TITLE
broken build with 4.0.0

### ISSUE THREAD

**Issue by pduchesne** [qoomon/maven-git-versioning-extension#24]
Hello,

the 4.0.0 that's been released last night breaks our builds with the following error : 

> Non-readable POM *redacted*/pom.xml: Git Versioning Model Processor: Element 'branches' does not have a match in class me.qoomon.maven.gitversioning.GitVersioningExtensionConfiguration at line 2

Are there known breaking changes that we should be aware of ? Release notes ?

Our configuration: 
```
<configuration>
    <branches>
        <branch>
            <!-- it appears that the standard config (using prefix) does not work
                 -> reimplement it using regex capture                             -->
            <pattern><![CDATA[release/(?<release>.*)]]></pattern>
            <versionFormat>${release}-SNAPSHOT</versionFormat>
        </branch>
    </branches>
    <tags>
        <tag>
            <!-- same as above -->
            <pattern><![CDATA[v(?<foo>.*)]]></pattern>
            <versionFormat>${foo}</versionFormat>
        </tag>
    </tags>
    <commit>
        <versionFormat>${commit}</versionFormat>
    </commit>
</configuration>
```

**Comment by qoomon** [comment]
Oh I'm so sorry yes forgot to point that out one moment I will write them down.
I released a version for gradle as well and aligned them.

**Comment by qoomon** [comment]
[![Changelog](https://badgen.net/badge/changelog/%E2%98%85/blue)](https://github.com/qoomon/maven-git-versioning-extension/blob/master/README.md#changelog)

**Comment by pduchesne** [comment]
Alright, makes sense now. Thank you.
