### ISSUE TITLE
Select newest/highest version tag for building

### ISSUE THREAD

**Issue by cboehme** [qoomon/maven-git-versioning-extension#250]
I have come across an issue when building a commit which has multiple tags which are matched by a single ref config. I excepted that the maven-git-versioning-extension would select the newest tag or the highest version number. However, the tag representing the lowest version number was selected.

To illustrate: a commit is tagged with _release/3.0.0_ and _release/3.0.1_. When building this commit I expect release 3.0.1 to be built but instead version 3.0.0 is built.

 I think the problem is in [line 750 in GitVersioningModelProcess](https://github.com/qoomon/maven-git-versioning-extension/blob/7927c9aab41a69775e628591766b061f240fbad7/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L750), where the list of tags is sorted ascendingly by the comparator defined by `DefaultArtifactVersion`. Before this sort happens the list of tags is sorted by the order defined in [TagComparator](https://github.com/qoomon/maven-git-versioning-extension/blob/7927c9aab41a69775e628591766b061f240fbad7/src/main/java/me/qoomon/gitversioning/commons/TagComparator.java#L14) (called in [line 150 in GitUtil.java](https://github.com/qoomon/maven-git-versioning-extension/blob/7927c9aab41a69775e628591766b061f240fbad7/src/main/java/me/qoomon/gitversioning/commons/GitUtil.java#L115)). The order defined in `TagComparator` is the one I expect to be used when selecting the tag for building.

**Comment by qoomon** [comment]
Should be fixed in version `9.6.6` :-)
Thanks for reporting
