### ISSUE TITLE
Github-Repository not up-to-date?

### ISSUE THREAD

**Issue by cboehme** [qoomon/maven-git-versioning-extension#251]
The repository here on Github does not seem to be up-to-date: The latest version of the maven-git-versioning-extension on Maven Central is 9.6.6, released on August 22, 2023. In the repository here on Github, however, the last commit on master was made on 30 March, 2023 and the latest release is 9.6.4. Am I looking in the wrong place?

**Comment by qoomon** [comment]
thanks so much I forgot to push :-). Should be up to date again.

**Comment by cboehme** [comment]
Great, thank you!
