### ISSUE TITLE
Describe should not return current tag from describe

### ISSUE THREAD

**Issue by mkleczek** [qoomon/maven-git-versioning-extension#252]
My use case is to find the previous release version using describe.

Unfortunately for builds executed from tag - current tag is returned.

**Comment by qoomon** [comment]
Could you share Your config? And why would you not use the tag version?

**Comment by mkleczek** [comment]
Hi, sorry for such a brief description.
The whole use case is as follows:

1. My project is a library (jar) with database migration (Liquibase) scripts
2. I want to make sure the subsequent versions of the library can be deployed on top of a previous version
3. So I configured some tests that based on the previous version number download the jar from Maven repo, execute previous version migration scripts and only then execute current version scripts.
4. Everything works fine if we run tests from the branch but once we run tests from the tag - describe does not return previous but current version tag. The tests don't work since the jar is not yet in the repo.

I am wondering if there is a way to somehow resolve it.

**Comment by qoomon** [comment]
That's a tricky situation :-)
My suggestion is so explicitly set a branch via environment `export VERSIONING_GIT_BRANCH=...` variable while running your tests,
