### ISSUE TITLE
Change the default location of .git-versioned.pom.xml to a folder inside target-folder 

### ISSUE THREAD

**Issue by florianli** [qoomon/maven-git-versioning-extension#28]
The `.git-versioned.pom.xml` is always generated when maven build is executed. Therefore it should not be stored in git. In your current plugin-configuration the default folder of `.git-versioned.pom.xml` is `currentProject.getBasedir()`. I think, it is common for a maven-project, that generated files are stored inside the target-folder. 
- the maven-clean-plugin doesn't need extra configuration to delete the file. 
- the target-folder is usually ignored via `.gitignore`

**Comment by qoomon** [comment]
That was my first implementation, then I found out that some maven plugins from apache acts this way. However I can revert this change an put it the target folder again.

**Comment by florianli** [comment]
I can remember that it worked that way in a previous version. #29 looks good to me.

**Comment by qoomon** [comment]
implemented in version `v4.0.3`

**Comment by qoomon** [comment]
@florianli I've just recognised that the official [maven flatten plugin](https://www.mojohaus.org/flatten-maven-plugin/) put its `.flattened-pom.xml` next to the original `pom.xml` as-well. 
We may should follow the standard? What do you think? actually it's quite easy to exclude all artificial `pom.xml` files git ignore patten would look like this `.*-pom.xml`

**Comment by florianli** [comment]
I don't have any opinion on this, except it should be inside the target-folder. I can have a look at the maven documentation tomorrow, if you want. Mayby I find something about this topic. -------- Originalnachricht --------Betreff: Re: [qoomon/maven-git-versioning-extension] Change the default location of .git-versioned.pom.xml to a folder inside target-folder  (#28)Von: Bengt Brodersen An: qoomon/maven-git-versioning-extension Cc: Florian Lindermaier ,Mention @florianli I've just recognised that the official maven flatten plugin put its .flattened-pom.xml next to the original pom.xml as-well.
We may should follow the standard? What do you think? actually it's quite easy to exclude all artificial pom.xml files git ignore patten would look like this .*-pom.xml

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qoomon/maven-git-versioning-extension","title":"qoomon/maven-git-versioning-extension","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/qoomon/maven-git-versioning-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@qoomon in #28: @florianli I've just recognised that the official [maven flatten plugin](https://www.mojohaus.org/flatten-maven-plugin/) put its `.flattened-pom.xml` next to the original `pom.xml` as-well. \r\nWe may should follow the standard? What do you think? actually it's quite easy to exclude all artificial `pom.xml` files git ignore patten would look like this `.*-pom.xml`"}],"action":{"name":"View Issue","url":"https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477657098"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477657098",
"url": "https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477657098",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by qoomon** [comment]
that would be great

**Comment by qoomon** [comment]
I just found kinda explanation why they choose to place the modified pom file next to the original https://github.com/mojohaus/flatten-maven-plugin/issues/50
I also found out that that the flatten plugin hase a clean goal that is registered to the clean phase.
So I think I will revert the location back to next to the original pom file and a this clean task.
What do you think?

**Comment by florianli** [comment]
I think I made my point quite clear with this issue. But in the end it is your desicion. When it is next to the original pom I will add a pattern to. gitignore to avoid that someone will commit the file to git-------- Originalnachricht --------Betreff: Re: [qoomon/maven-git-versioning-extension] Change the default location of .git-versioned.pom.xml to a folder inside target-folder  (#28)Von: Bengt Brodersen An: qoomon/maven-git-versioning-extension Cc: Florian Lindermaier ,Mention I just found kinda explanation why they choose to place the modified pom file next to the original mojohaus/flatten-maven-plugin#50
I also found out that that the flatten plugin hase a clean goal that is registered to the clean phase.
So I think I will revert the location back to next to the original pom file and a this clean task.
What do you think?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qoomon/maven-git-versioning-extension","title":"qoomon/maven-git-versioning-extension","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/qoomon/maven-git-versioning-extension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@qoomon in #28: I just found kinda explanation why they choose to place the modified pom file next to the original https://github.com/mojohaus/flatten-maven-plugin/issues/50\r\nI also found out that that the flatten plugin hase a clean goal that is registered to the clean phase.\r\nSo I think I will revert the location back to next to the original pom file and a this clean task.\r\nWhat do you think?"}],"action":{"name":"View Issue","url":"https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477875099"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477875099",
"url": "https://github.com/qoomon/maven-git-versioning-extension/issues/28#issuecomment-477875099",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by qoomon** [comment]
@florianli  I think the problem mentioned in `mojohaus/flatten-maven-plugin#50` is fixed so I will leave the pom in the target directory.

**Comment by yankydoo** [comment]
It seems that starting with 6.0.0 the .git-versioned-pom.xml is generated next to the pom.xml again, not in the target directory. Was this an intentional change? If so, it would be great to add it to the changelog.

**Comment by qoomon** [comment]
It was intentional. I changed the location due to problems for some plugins with relative paths (relative to pom location).
I'll add a changelog entry. I'm sorry for the inconvenience.

**Comment by yankydoo** [comment]
Don't worry, no big deal. Thanks for the response!

**Comment by qoomon** [comment]
There are related issues in the flatten pom plugin, see:
* https://github.com/mojohaus/flatten-maven-plugin/issues/53
* https://github.com/mojohaus/flatten-maven-plugin/issues/94
As long as there is no real solution I'll will stay with the current solution, alike the flatten pom plugin behaviour.
