### ISSUE TITLE
Add Label when ${describe.distance} > 0

### ISSUE THREAD

**Issue by olivergondza** [qoomon/maven-git-versioning-extension#299]
First and foremost, this is a great project. Thanks for putting the effort in developing it!

---

I am trying to use dynamic versioning based on my tags + distance. That alone works well, until I need `deploy` plugin to make distinctions for release/snapshot based on the presence of the `-SNAPSHOT` label.

- In `maven-deploy-plugin` lingo, `-SNAPSHOT` is any work that is not intended to be a release. So it can be fully committed in git (not dirty), but that commit was not tagged/released to be deployed as a release.

- `maven-git-versioning-extension`'s `${dirty.snapshot}` adds `-SNAPSHOT` label whenever build from dirty git work tree.

I other words, I am looking for a way to add `-SNAPSHOT` label whenever `${describe.distance} > 0`.

Is there a way to do this? If not, can this be added?

**Comment by qoomon** [comment]
Hi there, this is not possible at the moment, however that is quite easy to implement.

What could be a proper name for that placeholder? `${describe.distance.snapshot}`? Do you have some better wording ideas?

**Comment by olivergondza** [comment]
Thanks. `${describe.distance.snapshot}` sounds great to me, yeah.

**Comment by qoomon** [comment]
released with version 9.8.0
