### ISSUE TITLE
Branch is added to version

### ISSUE THREAD

**Issue by jonasmyhre** [qoomon/maven-git-versioning-extension#3]
Trying to have the both version and branch as part of the snapshot name.

Current config snippet: 

`<branch>
<pattern>.*</pattern>
<versionFormat>${version.release}-${branch}-SNAPSHOT</versionFormat>
</branch>
</branches>`

Seems the branch is added to ${version.release}, as we get quite a long snapshot name after a few runs.
From pom version 1.0.7-SNAPSHOT after first run on branch "branch-deploy", the name is: 1.0.7-branch-deploy-branch-deploy-SNAPSHOT.

This keeps adding up:
1.0.5-branch-deploy-branch-deploy-branch-deploy-branch-deploy-SNAPSHOT

**Comment by qoomon** [comment]
Hi Jonas,

How do you solved it?

In general I can recommend to never use the f**king release plugin ever again.
My colleagues and me get rid of this plugin years ago.
```maven-git-versioning-extension``` tries to solve the need of such a plugin.
However you can use ```mvn version:set``` to change the version within the pom files and all child poms if you need to

Regards
Bengt

**Comment by jonasmyhre** [comment]
We haven't solved it yet. I'll post the solution if or when i find it! 

Thanks!

**Comment by qoomon** [comment]
May i can help you?
