### ISSUE TITLE
Extension replaces variables in profile activation

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#31]
Hi

great extension, but is has a showstopper bug for us.
The following code is replaced by the extension from:
```
<profile>
      <id>kotlin</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/kotlin</exists>
        </file>
      </activation>
...
</profile>
```
to
```
<profile>
  <id>kotlin</id>
  <activation>
    <file>
      <exists>C:\foo\bar\src\main\kotlin</exists>
    </file>
  </activation>
...
</profile>
```
which makes the generated pom useless for modules that want to inherit the profiles.

Kind regards,
Michael

**Comment by qoomon** [comment]
Hi, thanks for the report.
I will investigate during this week.

**Comment by qoomon** [comment]
I might have a solution but i have to test it more in depth, its a little tricky

**Comment by qoomon** [comment]
I think I've fixed it will release is tomorrow i think.

**Comment by qoomon** [comment]
should work in version `4.0.6`. I've just released it may take some minutes to be available.

**Comment by qoomon** [comment]
damn it i introduced a endless loop please ignore version `4.0.6` I will deploy the fixed version right away `4.0.7`

**Comment by qoomon** [comment]
would be great if you can confirm that it works for you as expected. have a nice weekend

**Comment by reitzmichnicht** [comment]
Fix looks good to me, works as expected now

**Comment by qoomon** [comment]
glad to hear that
