### ISSUE TITLE
Required Maven version

### ISSUE THREAD

**Issue by Kris-kun** [qoomon/maven-git-versioning-extension#318]
What exactly is the required Maven version for maven-git-versioning-extension 9.6.4+?
I tried using the newest version (9.8.1) with Maven 3.6.3, giving me the error message `The plugin me.qoomon:maven-git-versioning-extension:9.8.1 requires Maven version 3.6.4`.

Since version 9.6.4, it seems the maven prerequisite was switched from 3.6.3 to 3.6.4. The README states that the minimum Maven version should be 3.6.3, though this is not the case anymore.

So should the minimum Maven version be 3.6.3 (in this case, the prerequisite has to be changed) or should it be 3.6.4 or rather 3.8.1 because this is the next version after 3.6.3 (in this case, the README needs to be updated)?

**Comment by qoomon** [comment]
should be 3.6.4, I'll adjust the readme

**Comment by Kris-kun** [comment]
Okay, thanks.
