### ISSUE TITLE
Environment variable VERSIONING_GIT_BRANCH not working

### ISSUE THREAD

**Issue by Pooj2** [qoomon/maven-git-versioning-extension#32]
Bug: me.qoomon.maven.gitversioning.GitVersioningModelProcessor.getOption(String). The following line of code result to:
Actual:
VERSIONING_GIT.BRANCH
Expected:
VERSIONING_GIT_BRANCH

>  value = System.getenv("VERSIONING_" + name.replaceAll("[A-Z]", "_$0").toUpperCase());

See
> System.out.println("VERSIONING_" +"git.branch".replaceAll("[A-Z]", "_$0").toUpperCase());

at https://repl.it/languages/java.

**Comment by qoomon** [comment]
Just fixed it see 4f72baa. I will release a new version today

**Comment by reitzmichnicht** [comment]
ah thats why it does not work in the actual version

**Comment by qoomon** [comment]
should work again in version `4.0.5`
