### ISSUE TITLE
Wrong version with multi-module project and no parent POM

### ISSUE THREAD

**Issue by klinamen** [qoomon/maven-git-versioning-extension#34]
Maven does not enforce module POMs to have the main "packaging" POM as a parent, whereas me.qoomon.maven.gitversioning.ModelProcessor#findMvnDir assumes so.
This causes the configuration not to be found and the versioning scheme to fallback to the default "commit" when a single module is built from its module directory.
I am opening a pull request with a failing test and a potential fix.

**Comment by qoomon** [comment]
Fix release in v4.2.0
