### ISSUE TITLE
ClassCastException thrown when using maven-antrun-plugin in a build

### ISSUE THREAD

**Issue by yorkish** [qoomon/maven-git-versioning-extension#36]
We are using the latest version of your plugin (v4.1.0) and are seeing a raised exception in the build lifecycle when using it alonside another plugin "maven-antrun-plugin"

    Caused by: java.lang.ClassCastException: java.util.Properties cannot be cast to java.lang.String
    at org.apache.maven.plugin.antrun.AntRunMojo.copyProperties (AntRunMojo.java:406)

It fails to iterate over every Properties key/values.

I've look into your code an i'm seeing a setProperties that breaks the Javadoc on Properties.
(taken from [Oracle Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html?is-external=true))
>The Properties class represents a persistent set of properties. The Properties can be saved to a stream or loaded from a stream. Each key and its corresponding value in the property list is a string.

If you look closely in the class `ModelProcessor` at line 266, you are passing configs to the plugin using
`model.getProperties().put(...)`

Here is the offending code:

    // pass config to plugin
    Properties pluginConfig = new Properties();
    pluginConfig.setProperty("updatePom", Boolean.toString(updatePomOption));
    model.getProperties().put(VersioningMojo.class.getName(), pluginConfig);

Could you pass your configs in keys/values that are actual `String`s ?

Otherwise great work! really helpful!

**Comment by qoomon** [comment]
Give me a moment, I will fix it.

**Comment by qoomon** [comment]
Just released the fix version `4.1.1`, should be available in maven central in a couple of minutes.
Would be great if you confirm the fix.

**Comment by yorkish** [comment]
Great!

I'll check that first thing Monday morning!

Le jeu. 2 mai 2019 11 h 19, Bengt Brodersen <notifications@github.com> a
écrit :

**Comment by yorkish** [comment]
Sorry for the delay!
It works as excepted!
thumbs up!
