### ISSUE TITLE
Endless loop in ModelProcessor#findMvnDir during build on the third level module in a multimodule project

### ISSUE THREAD

**Issue by dornwelt** [qoomon/maven-git-versioning-extension#37]
Hi @qoomon, 

after the fix of Issue 34, I have one big problem during any builds on the third level module in a multimodule project. -> endless loop because the code line 245 in the ModelProcessor class. The parentPomFile is always taken from the projectModel and does not use parentModel variable.

In PR is my possible solution.

**Comment by qoomon** [comment]
Just released the fix version 4.2.1, should be available in maven central in a couple of minutes.
Would be great if you confirm the fix.

**Comment by dornwelt** [comment]
It looks good for me now. Many thanks!
