### ISSUE TITLE
Updating dependencies versions

### ISSUE THREAD

**Issue by thomasdelhomenie** [qoomon/maven-git-versioning-extension#41]
I plan to use this extension to manage the versions of our feature branches, but I have a case which does not seem to be covered by the extension.
Our project is composed of several git repositories, with dependencies between each others. So we have a project A in its own repository which depends on a project B also in its own repository. In the pom of the project A, I have the following dependency:
```
<version>1.0.0-SNAPSHOT</version>
...
<properties>
  <project.b.version>2.0.0-SNAPSHOT</project.b.version>
</properties>
...
<dependencies>
  <dependency>
      <groupId>my.group</groupId>
      <artifactId>project.b</artifactId>
      <version>${project.b.version}</version>
    </dependency>
</dependencies>
```
We need to work in parallel in both projects (some changes in project A requires some changes in project B).
The extension allows to replace the version of the module but I did not find a way to do it for  dependencies/properties. Is there a way to do it ?
If not, could it be an interesting improvement, or is it beyond the scope of this extension ?

**Comment by qoomon** [comment]
Interesting issue :-D
Do you want to replace a specific version property dependent on branch/tag?
Can you give me an example of how versions should change?

**Comment by qoomon** [comment]
Are the versions of project A and B somehow logically connected or is it possible to extrapolate from project version A to project version B?

**Comment by thomasdelhomenie** [comment]
Thank you for your answer!

Both projects have the same branch names, so for my feature my-killing-feature, I have a branch feature/my-killing-feature on both projects. When on this branch, I want to replace the version of both projects with the pattern <version>-<feature-name>-SNAPSHOT. So for example for project A, if its version is 1.0.x-SNAPSHOT, it will be 1.0.x-my-killing-feature-SNAPSHOT, and for project B, if its version is 2.0.x-SNAPSHOT, it will be 2.0.x-my-killing-feature-SNAPSHOT.
This works fine with the following configuration:

**.mvn/extensions.xml**
```xml
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">

   <extension>
       <groupId>me.qoomon</groupId>
       <artifactId>maven-git-versioning-extension</artifactId>
       <version>LATEST</version>
   </extension>

</extensions>
```

**.mvn/maven-git-versioning-extension.xml**
```xml
<gitVersioning>
   <branch>
        <pattern><![CDATA[^(?!feature/).*$]]></pattern>
        <versionFormat>${version}</versionFormat>
    </branch>
   <branch>
        <pattern><![CDATA[feature/(?<feature>.+)]]></pattern>
        <versionFormat>${version.release}-${feature}-SNAPSHOT</versionFormat>
    </branch>
</gitVersioning>
```

I would like to apply the same change on some properties. Properties can be referred by their name directly (I don't have a lot), or ideally by a regex.

I guess this could be achieved by adding a new tag under branch tag in .mvn/maven-git-versioning-extension.xml file, something like :
```xml
    <branch>
        <pattern><![CDATA[feature/(?<feature>.+)]]></pattern>
        <versionFormat>${version.release}-${feature}-SNAPSHOT</versionFormat>
        <properties>
          <name>my.property.name</name>
          <propertyFormat>${property.version.release}-${feature}-SNAPSHOT</name>
        </properties>
    </branch>
```

I talk about properties because I think it is a best practice to define dependencies version in properties, but the final goal is to update the version of the dependencies, so there is maybe a better option.

**Comment by qoomon** [comment]
Hmm interesting idea. what about following structure.
```xml
<branch>
        <pattern><![CDATA[feature/(?<feature>.+)]]></pattern>
        <versionFormat>${version.release}-${feature}-SNAPSHOT</versionFormat>
        <property>
               <pattern>my.property.name</name>
               <value>
                      <pattern><![CDATA[(?<property.version.release>.+?)(-SNAPSHOT)?]]></name>
                      <format>${property.version.release}-${feature}-SNAPSHOT</format>
               </value>
        </property>
    </branch>
``` 

however I can't guarantee that I'm able to implement this in an easy way, so it might take a while

**Comment by thomasdelhomenie** [comment]
Looks better :+1: 

> however I can't guarantee that I'm able to implement this in an easy way, so it might take a while

No problem, I understand. Let me know if I can help. And thanks again!

**Comment by thomasdelhomenie** [comment]
I proposed a PR for this improvement : https://github.com/qoomon/maven-git-versioning-extension/pull/43
WDYT ?

**Comment by qoomon** [comment]
release within version `4.4.0`

**Comment by qoomon** [comment]
please confirm, if everything is working as expected

**Comment by thomasdelhomenie** [comment]
Thanks. Ok I will check that.

**Comment by lmartineaumdf** [comment]
@thomasdelhomenie  are you able to make it work with the new property feature ? I'm currently pointing to the 4.4.0 release and can't make it work.. it does not replace my property like your branch (PR) did. Can you help me to find out why ?
Config look like this (tried to simplify as much as I could to isolate the problem):

<gitVersioning>
  <...>
    <branch>
         <pattern><![CDATA[feature/(?<feature>.+)]]></pattern>
         <versionFormat>${feature}-SNAPSHOT</versionFormat>
	 <property>
           <pattern>revision</pattern>
           <value>
               <pattern>pomfilevalue</pattern>
                <format>extensionvalue</format>
           </value>
         </property>         
     </branch>
  <...>
</gitVersioning>

The version is replaced correctlly but the property value never get replaced, whatever the pattern I'm using. It was working fine with your branch (?). Maybe I'm missing something ?

**Comment by qoomon** [comment]
I've just added property replacement configuration to https://github.com/qoomon/maven-git-versioning-extension/tree/master/src/test/resources/testProjects/standardProject

you can verify it works by execute `mvn help:evaluate -q -DforceStdout -Dexpression=foo`
where foo is the parameter that is replaced by the git versioning configuration of standard test project
it should print `new_new_new`

For me it works like expected. Does this config work for you as well?

**Comment by lmartineaumdf** [comment]
@qoomon Thanks I finallly figured it out. My project is a little complex here. I have maven modules so I`m using the flattened-maven-plugin. The property replacement doesn't work when I run the mvn command at the sub-module level but it works great when I run the mvn command at the root project level.

**Comment by thomasdelhomenie** [comment]
@lmartineaumdf good to hear you made it work!

I did a test on my side, it works fine with the release 4.4.0, thanks @qoomon :+1: 
I just noticed one thing, in the logs all the properties are listed even if they have not been changed. For example in the following output, only the last property has been really updated (org.exoplatform.platform.version):
```
[INFO] task-management - set project version to 2.3.x-news-SNAPSHOT (branch:feature/news)
[INFO] task-management - set property org.webjars.selectize.js.version to 0.12.1 (branch:feature/news)
[INFO] task-management - set property org.antlr.version to 3.4 (branch:feature/news)
[INFO] task-management - set property org.webjars.bootstrap-datepicker.version to 1.4.0 (branch:feature/news)
[INFO] task-management - set property project.build.sourceEncoding to UTF-8 (branch:feature/news)
[INFO] task-management - set property h2database.version to 1.2.145 (branch:feature/news)
[INFO] task-management - set property mockito.version to 2.0.13-beta (branch:feature/news)
[INFO] task-management - set property org.juzu.version to 1.2.x-SNAPSHOT (branch:feature/news)
[INFO] task-management - set property org.webjars.jquery-ui.version to 1.11.4 (branch:feature/news)
[INFO] task-management - set property org.webjars.select2.version to 3.5.2 (branch:feature/news)
[INFO] task-management - set property org.webjars.x-editable-bootstrap.version to 1.4.6 (branch:feature/news)
[INFO] task-management - set property org.exoplatform.platform.version to 5.3.x-news-SNAPSHOT (branch:feature/news)
```
Shouldn't we log only the updated properties ? Or maybe say if it has been changed or not for each one ? WDYT ?

**Comment by qoomon** [comment]
@thomasdelhomenie you are right. I will change it.

**Comment by qoomon** [comment]
fixed in release version `4.4.1`

**Comment by thomasdelhomenie** [comment]
Cool! great reactivity :+1:
It seems there is a type in the version number, it is `4.4.1mu` instead of `4.4.1` (see in [pom](https://github.com/qoomon/maven-git-versioning-extension/blob/master/pom.xml#L10) and in [maven central](https://search.maven.org/search?q=a:maven-git-versioning-extension)).

**Comment by qoomon** [comment]
oh damn it. mabey to quick reactivity :-D
I will fix it

**Comment by qoomon** [comment]
I've fixed the version number and uploaded it to maven central again.
thx for reporting, and sorry for the trouble

**Comment by thomasdelhomenie** [comment]
Thanks, the version is ok now :+1: 
About the logs, it works fine for the parent pom but not for submodules since `virtualProjectModel.getProperties().getProperty(property.getKey())` is null in this case.
