### ISSUE TITLE
Empty properties are overwritten

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#45]
We see a regression with version 4.4.1

Following structure:
PARENT (property: <sonar.tests>src/test</sonar.tests>)
- Module1 (property: <sonar.tests></sonar.tests>)

When running with versioning extension the property in Module1 is updated to the value of the parent.

Kind regards,
Michael

**Comment by qoomon** [comment]
I'm investigating

**Comment by qoomon** [comment]
I found the bug, see master branch. I will test it a little further and release a new version tomorrow.

**Comment by qoomon** [comment]
Try version `4.4.2`

**Comment by reitzmichnicht** [comment]
Works as expected now, thanks for the quick fix.

**Comment by qoomon** [comment]
np
