### ISSUE TITLE
Property variables are replaced

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#47]
This is a regression from 4.4.0 to 4.4.3
Having the following properties in my pom.xml:
```
<properties>
    <skipTests>false</skipTests>
    <skipUTs>${skipTests}</skipUTs>
    <skipITs>${skipTests}</skipITs>
    <scm-commit>${git.commit}</scm-commit>
    <scm-branch>${git.branch}</scm-branch>
</properties>
```

This is now resolved by this extension to:
```
    <skipTests>false</skipTests>
    <skipUTs>true</skipUTs>
    <skipITs>true</skipITs>
    <scm-commit>0d434d66a1e2f9aa10d78f9ab8198ce4a789ea02</scm-commit>
    <scm-branch>master</scm-branch>
```

Kind regards,
Michael

**Comment by qoomon** [comment]
And what is the expected behaviour?

**Comment by qoomon** [comment]
And may you provide your extension config as well?

**Comment by qoomon** [comment]
Ah understand, strange behaviour. Will fix it in the evening

**Comment by reitzmichnicht** [comment]
The expected behaviour is that the extension leave the properties as they are.

**Comment by qoomon** [comment]
Sorry it was early in the morning :-D of course it should not change the properties.
I fixed it already. Will release it in a couple of minutes.

**Comment by qoomon** [comment]
done. version `4.4.4` was just released

**Comment by reitzmichnicht** [comment]
Works again as expected. Thank you
