### ISSUE TITLE
Usage with ear projects

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#48]
We are using this plugin (v1.2.0) for our `jar` and `war` builds and are quite happy with it. We are wanting to do the same for our `ear` applications but are not sure how it would work and was wondering if there was any advice you can give.

The simple case we are looking at is a project that needs to be generated and output as an ear, but all it has is a single web project in it (war). We're not sure on the best way to structure the war/ear projects, but we are thinking we will have two Maven projects. The war project will look as normal for our web application, and the ear will reference that same war for its bundling.

We're not sure if we'd need to run multiple build steps: one for war and one for ear?

Any advice you could give would be great. Thank you!

**Comment by l3ender** [comment]
One important thing that I don't feel I explained well: our `ear` project won't be referencing a separate `war` module that is already built/deployed to our Maven repo--it will instead be generating output based on the current branch that is being built.

**Comment by qoomon** [comment]
May you can upload a simple project with your setup?
And  can you explain once again what is not working right now (current and expected result)?

**Comment by l3ender** [comment]
I believe I've got it working. I wasn't experiencing any specific issue, but was more wondering on use case and how to structure the projects. After doing more research it was clear that I should look at a multi-module project setup like the following:

    my-app/
    |__.mvn/
    |__pom.xml (parent)
    |__ear/
       |__pom.xml
    |__war/
       |__pom.xml
       |__src/...

After I nailed the project structure, this plugin was working perfectly.

**Comment by qoomon** [comment]
Glad to hear that.
