### ISSUE TITLE
Question: update changelog

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#49]
We are currently using this plugin and it's working great. We are on a specific version (1.2.0) and I'm doing some work in our project structure and wondering about upgrading to the latest as it would be an ideal time. However I'm not sure of reason/rationale for us to do so and if it would be necessary or desirable.

I do see the breaking changes in README, but I'm curious if there were other features or enhancements that have been added that would prompt us to get on the latest?

Any advice would be appreciated.

**Comment by qoomon** [comment]
Bug Fixes and some Features
* update original pom to dedicated version
* update properties based on tag or branch
* Minimize logging
