### ISSUE TITLE
Version release number in tag loses digit

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#5]
I am integrating maven-git-versioning-extension and am facing the following issue. My project's pom file has the following version: `<version>1.0.0-SNAPSHOT</version>`

However, when I try and release, the version that is generated by the extension is `1.0` instead of `1.0.0`, and the incremented version is `1.1` instead of `1.0.1`:

```
$ mvn release:prepare -DdryRun=true -Dresume=false -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] --- maven-git-versioning-extension:1.1.0 ---
[INFO] common-lib:1.0.0-SNAPSHOT -> version: single-artifact-maven-builds-SNAPSHOT
[INFO]
[INFO] ------------------------< org.company:common-lib >------------------------
[INFO] Building common-lib single-artifact-maven-builds-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ common-lib ---
[INFO] Verifying that there are no local modifications...
[INFO]   ignoring changes on: **\pom.xml.next, **\release.properties, **\pom.xml.branch, **\pom.xml.tag, **\pom.xml.backup, **\pom.xml.releaseBackup
[INFO] Executing: cmd.exe /X /C "git rev-parse --show-toplevel"
[INFO] Working directory: C:\Repositories\common-lib
[INFO] Executing: cmd.exe /X /C "git status --porcelain ."
[INFO] Working directory: C:\Repositories\common-lib
[WARNING] Ignoring unrecognized line: ?? .mvn/maven-git-versioning-extension.xml
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? release.properties
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "common-lib"? (org.company:common-lib) 1.0: :
What is SCM release tag or label for "common-lib"? (org.company:common-lib) common-lib-1.0: :
What is the new development version for "common-lib"? (org.company:common-lib) 1.1-SNAPSHOT: :
```

My maven-git-versioning-extension.xml file is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<branches>
		<branch>
			<pattern>master</pattern>
			<versionFormat>${version.release}</versionFormat>
		</branch>
		<branch>
			<pattern>artifact/.*</pattern>
			<prefix>artifact/</prefix>
			<versionFormat>${version.release}-${branch}-SNAPSHOT</versionFormat>
		</branch>
	</branches>
	<tags>
		<tag>
			<pattern>.*</pattern>
			<versionFormat>${version.release}</versionFormat>
		</tag>
	</tags>
</configuration>
```

If I disable the extension via the command line argument, I see the correct versions:

```
$ mvn release:prepare -DdryRun=true -Dresume=false -DgitVersioning=false -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] --- maven-git-versioning-extension:1.1.0 ---
[INFO] Disabled.
[INFO]
[INFO] ------------------------< org.company:common-lib >------------------------
[INFO] Building common-lib 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ common-lib ---
[INFO] Verifying that there are no local modifications...
[INFO]   ignoring changes on: **\pom.xml.next, **\release.properties, **\pom.xml.branch, **\pom.xml.tag, **\pom.xml.backup, **\pom.xml.releaseBackup
[INFO] Executing: cmd.exe /X /C "git rev-parse --show-toplevel"
[INFO] Working directory: C:\Repositories\common-lib
[INFO] Executing: cmd.exe /X /C "git status --porcelain ."
[INFO] Working directory: C:\Repositories\common-lib
[WARNING] Ignoring unrecognized line: ?? .mvn/maven-git-versioning-extension.xml
[WARNING] Ignoring unrecognized line: ?? pom.xml.next
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? pom.xml.tag
[WARNING] Ignoring unrecognized line: ?? release.properties
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "common-lib"? (org.company:common-lib) 1.0.0: :
What is SCM release tag or label for "common-lib"? (org.company:common-lib) common-lib-1.0.0: :
What is the new development version for "common-lib"? (org.company:common-lib) 1.0.1-SNAPSHOT: :
```

Please advise. Thank you!

**Comment by l3ender** [comment]
It seems like I'm having trouble with any type of configuration for the `tag`:

```
<tags>
	<tag>
		<pattern>.*</pattern>
		<versionFormat>abc123</versionFormat>
	</tag>
</tags>
```

Produces output like the following:
```
$ mvn release:prepare -DdryRun=true -Dresume=false -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] --- maven-git-versioning-extension:1.1.0 ---
[INFO] common-lib:1.0.0-SNAPSHOT -> version: single-artifact-maven-builds-SNAPSHOT
[INFO]
[INFO] ------------------------< org.company:common-lib >------------------------
[INFO] Building common-lib single-artifact-maven-builds-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ common-lib ---
[INFO] Verifying that there are no local modifications...
[INFO]   ignoring changes on: **\pom.xml.next, **\release.properties, **\pom.xml.branch, **\pom.xml.tag, **\pom.xml.backup, **\pom.xml.releaseBackup
[INFO] Executing: cmd.exe /X /C "git rev-parse --show-toplevel"
[INFO] Working directory: C:\Repositories\common-lib
[INFO] Executing: cmd.exe /X /C "git status --porcelain ."
[INFO] Working directory: C:\Repositories\common-lib
[WARNING] Ignoring unrecognized line: ?? pom.xml.next
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? pom.xml.tag
[WARNING] Ignoring unrecognized line: ?? release.properties
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "common-lib"? (org.company:common-lib) 1.0: :
What is SCM release tag or label for "common-lib"? (org.company:common-lib) common-lib-1.0: :
What is the new development version for "common-lib"? (org.company:common-lib) 1.1-SNAPSHOT: :
```

So it seems like the tag configuration I have isn't working at all. Any advice would be appreciated. Thanks!

**Comment by qoomon** [comment]
I will have look at this, later this day

**Comment by qoomon** [comment]
I think your first problem is caused by no matching branch pattern.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<branches>
		<branch>
			<pattern>master</pattern>
			<versionFormat>${version.release}</versionFormat>
		</branch>
		<branch>
			<pattern>artifact/.*</pattern>
			<prefix>artifact/</prefix>
			<versionFormat>${version.release}-${branch}-SNAPSHOT</versionFormat>
		</branch>
	</branches>
	<tags>
		<tag>
			<pattern>.*</pattern>
			<versionFormat>${version.release}</versionFormat>
		</tag>
	</tags>
</configuration>

``` 

the default branch pattern '.*' will generate version in the form of <BRANCH_NAME>-SNAPSHOT
in your case it seams you are on a branch called *single-artifact-maven-builds*
see following log line
``` [INFO] common-lib:1.0.0-SNAPSHOT -> version: single-artifact-maven-builds-SNAPSHOT ```
if you want to overwrite the default version pattern a an entry with patten '.*' and set it to something like '${version}'

at my current company we don't set version anymore  in the pom we set it to a static version of '0.0.0-SNAPSHOT' ad we only use tags for versioning and branch version a just {branch}-SNAPSHOT

**Comment by qoomon** [comment]
The second problem is may caused by the same problem, do have a tag on the current commit you are building on?

**Comment by qoomon** [comment]
can you provide me your current git branch (```git branch```) and current tag (```git tag -l --points-at HEAD```)?

**Comment by l3ender** [comment]
Thanks for the follow up. You're right--I didn't have a branch name matching the branch pattern, so it was falling back to the default (I had been testing on a different branch and then switched).

I do not have a tag on the current head, which must be why the `tag` directive isn't being picked up. I'll look at more.

In general, could you advise how you use the extension? I'd also like to keep a static version in our pom files and **not** use the maven release command where it auto-increments the pom's version. This will work for our snapshot builds, but I'm unsure how this would work for master builds, where we do want to increment the version. Do you have some other part of your CI environment perform incremental tagging (based on previous tag version), so that when the maven build runs it is able to reference the updated version?

Your help is appreciated. Thank you!

**Comment by l3ender** [comment]
I should also note that I was hoping to avoid creating tags for every snapshot build. Not sure if what I'm looking to do is possible out of the box.

**Comment by l3ender** [comment]
Hi, any advice you could give on how you use the extension for master builds? Are you having your CI environment doing tagging, or are you using the Maven deploy goal? Thanks!

**Comment by qoomon** [comment]
Hi, the following config is like we use it at `moebel.de` 
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<branches>
		<branch>
			<pattern>.*</pattern>
			<versionFormat>${branch}-SNAPSHOT</versionFormat>
		</branch>
	</branches>
	<tags>
		<tag>
			<pattern>v[0-9].*</pattern>
			<prefix>v</prefix>
			<versionFormat>${tag}</versionFormat>
		</tag>
	</tags>
</configuration>
```
in the pom.xml we set `<version>0-SNAPSHOT>`

This setup will lead to following versions

on every branch even on master it will result in versions like
* branch: feature/moonshot -> feature-moonshot-SNAPSHOT
* branch: master                    -> master-SNAPSHOT

if you build on a tag i will result in
* tag: v1.0.0           -> 1.0.0
* tag: v2.1.0-beta -> 2.1.0-beta

we use gitlab for CI and this is all you need to setup
```yaml
##### GitLab CI Setup
```yml
before_script:
  - export MAVEN_PROJECT_BRANCH=$CI_COMMIT_REF_NAME
  - export MAVEN_PROJECT_TAG=$CI_COMMIT_REF_NAME
```

## our workflow
we just push to our branches which will result in branch versions.
if we want to release a specific commit we tag it and a release version in build automagically
that's it, since I wrote this extension we've never edit the pom.xml <version> tag again,
and we really like it, never ever merge conflict on versions again :-D

I hope this will help you.

**Comment by qoomon** [comment]
And we don't use the release plugin at all just the deploy goal.
To check no snapshot dependencies are used we use the https://maven.apache.org/enforcer/enforcer-rules/requireReleaseDeps.html

**Comment by l3ender** [comment]
Thank you--that helps. The component I was missing was that you were manually tagging when ready to perform a release. I think I can set up our CI to do that without much hassle.

Appreciate it!

**Comment by qoomon** [comment]
You're welcome! Please tell me if this workflow fill your needs. I am really interested in getting feedback.

**Comment by l3ender** [comment]
I'm curious to get more feedback from you if possible.

Do you find any pain points with needing to manually tag? I am struggling to think through a good way for us to accomplish this automatically and to avoid manual tags. We treat a merge to master as a "release" so for our workflow, master-SNAPSHOT is not applicable. Master branch is always clean and always represents production ready.

I'm thinking that our master build will need to differ from other builds and have a separate step to determine next tag version and to apply that tag, prior to performing a build. This seems like a lot to manually perform but when I look around it seems like no one is doing anything automated for tagging/releasing so I'm not sure how to best proceed.

Our current build automation is done using Ant and we do the above as described. The model works well for us and I'm trying to replicate the same in Maven, but have found it difficult because of Maven's model. Feedback is helpful because I might be stuck too much thinking with how we already are doing things--a fresh perspective is beneficial.

Thank you!

**Comment by qoomon** [comment]
I worked with your workflow for quite while, however its has it drawbacks
* for example you can only release from master, its not possible to release alpha beta versions.
* it is really hard to automate versioning cause it impossible to determine if its a bug fix or a feature with breaking changes. This is only possible if make no faults on you commit messages, therefore we decided to create versions by hand
so in the end we are quite happy with the tag release workflow for over a year now.

with this maven extension you can set the version either by tags (see above) or just by pom version see example configuration
```xml
<configuration>
	<branches>
		<branch>
			<pattern>master</pattern>
			<versionFormat>${version.release}</versionFormat>
		</branch>
		<branch>
			<pattern>.*</pattern>
			<versionFormat>${branch}-SNAPSHOT</versionFormat>
		</branch>
	</branches>
</configuration>
```

in your ci on your master branch you just read the version and create a git tag
```bash
VERSION=$(mvn exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q)
git tag -a "v$VERSION" -m "version $VERSION"
```
