### ISSUE TITLE
Does not work with maven 3.6.2

### ISSUE THREAD

**Issue by nelbrecht** [qoomon/maven-git-versioning-extension#51]
Although it works consistently with maven 3.6.1, including the output of lots of warnings when `-Dversioning.disable=true` is given, it seems that with maven 3.6.2 there is no version processing at all, i.e.

- `mvn --non-recursive exec:exec -Dversioning.disable=true -Dexec.executable='echo' -Dexec.args='${project.version}'` does not give warnings
- `mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q` does not give a processed version

References:
- list of candidate changes: https://maven.apache.org/docs/3.6.2/release-notes.html

**Comment by qoomon** [comment]
They changed the way they used plexus container. Have no clue how to fix that.
My /src/main/java/me/qoomon/maven/gitversioning/ModelProcessor.java is still initialised, however never used.

**Comment by qoomon** [comment]
Related maven mailing list thread
https://lists.apache.org/thread.html/c2304f78d462a0c594543615222183cbed739437dcb8afcec323c565@%3Cusers.maven.apache.org%3E

**Comment by jens-meiss** [comment]
same here, it's not working with the latest maven docker image:

* maven:3.6-jdk-8-slim

but it works with:

* maven:3.6.1-jdk-8-slim

**Comment by qoomon** [comment]
Maven changed something how the load component. By this they've broken the functionality of overloading the ModelProcessor Component
I've tried to fix it without any success.

**Comment by jens-meiss** [comment]
then we have to wait for the maven bugfix, thx anyway :)

**Comment by qoomon** [comment]
I found a quite hacky workaround (0f649b951294bde8eecf8c391d75fddb3aaf0ad4), however its working again.
Will release a new version.

**Comment by qoomon** [comment]
Version `4.5.1` is released and should work with maven `3.6.2` again.

**Comment by qoomon** [comment]
@jens-meiss @nelbrecht Can you confirm it is working again?

**Comment by jens-meiss** [comment]
yes, works again with docker image: maven:3.6-jdk-8-slim

thx for the fast support! :)
