### ISSUE TITLE
Is there IDE-support?

### ISSUE THREAD

**Issue by heilbad** [qoomon/maven-git-versioning-extension#52]
Hello out there,
thanks a lot for providing this extension!

I have a multi-module-setup with a lot of modules here with the configuration of the extension at top-level. Modules get installed/deployed with "module-1.2.3-feature-abc-SNAPSHOT" instead of the default branch name "module-1.2.3-SNAPSHOT".
My use-case now is that I want to open only some of the modules in the IDE (here Eclipse with m2e). The rest of the modules should be resolved from the local repository.
Instead of resolving the module branch specific ("module-1.2.3-feature-abc-SNAPSHOT"), Eclipse seems to look for "module-1.2.3-SNAPSHOT".

Is IDE-support given in general and should I search for a problem in my setup?
The only solution I see is to use the "updatePom" option, which will alter all pom-files presumably causes merge conflicts when the branches get merged back.

**Comment by qoomon** [comment]
Hmm, you could disable the extension by setting environment variable or providing cli option

* Environment Variables
  * `export VERSIONING_DISABLE=true`
* Command Line Parameters
  * `maven ... -Dversioning.disable=true´

**Comment by qoomon** [comment]
In general I've not implemented any IDE specific behaviour, however I'm open minded to suggestions

**Comment by heilbad** [comment]
Switching it off would not make sense. My main use case for the extension would be to offer Nexus-support on feature-branches for developers.  

I quickly had a look at IntelliJ. Without knowing really much about that IDE at least the dependency resolution of opened projects is routed through the dependency and jars are found.

Strangely in Eclipse building with the embedded runtime shows the same results as builds with standalone maven on the command line. Different to that, the projects opened have the libraries without the feature-branch addition coming from the extension. 

I think the problem is how the Eclipse maven integration (m2e) is designed. I will try to ask there.

**Comment by heilbad** [comment]
Just for the record, reproduced with the multi-module-project in Eclipse (fails, looks for 0.0.0):
![grafik](https://user-images.githubusercontent.com/20524095/65306412-977a0380-db85-11e9-950d-4ffed0577d2d.png)

And in IntellijJ (is working, looks for "12", branch is "release/12"):
![grafik](https://user-images.githubusercontent.com/20524095/65306532-dd36cc00-db85-11e9-9f83-1f32fa170e1a.png)

**Comment by qoomon** [comment]
thx

**Comment by qoomon** [comment]
@heilbad  have you ever found a solution?
