### ISSUE TITLE
differences with jgitver?

### ISSUE THREAD

**Issue by roelal** [qoomon/maven-git-versioning-extension#53]
How is this different from [jgitver](https://github.com/jgitver/jgitver-maven-plugin)? You and @McFoggy both seem to have the same goals/ideas. But 2 different implementations have arised. Both actively worked on. Which one should I choose?

**Comment by qoomon** [comment]
Actually maven-git-versioning-extension roots are jgitver, however I did a total rewrite, adjusted structure and features to my needs. 

Some new features are:
* branch and tag specific versioning 
  * match branch or tag by regex patterns
  * [highly customisable](https://github.com/qoomon/maven-git-versioning-extension#version-format--placeholders)
* set parameters accordingly to branch or tag
* updating pom.xml 

So obviously I would recommend maven-git-versioning-extension :-D

**Comment by roelal** [comment]
Thx. I went with jgitver eventually. Because it has a feature to calculate the version based on previous (parent commit) tags, similar to `git-describe`. I couldn't find that in maven-git-versioning-extension. Correct me if I'm wrong.

**Comment by qoomon** [comment]
Thats right, I did not implement this feature by purpose.
I think it is a bad idea to have potential volatile version.

**Comment by qoomon** [comment]
@roelal however you might be interested in https://github.com/qoomon/git-conventional-commits the version command will calculate the version based on your commit messages.

**Comment by igroeg** [comment]
@qoomon is there a way to combine current branch and latest tag in the version name?

**Comment by qoomon** [comment]
@igroeg currently it is not possible, cause my extension only considers current commit without any knowledge about commit history. However I worked on a feature that includes your requirement see branch [feature/git-describe](https://github.com/qoomon/maven-git-versioning-extension/tree/feature/git-describe).

At the moment I have little time to work on it. Current state of the branch is that the describe command is working. That means I'll be able to provide version placeholders like `${describe.tag}` `${describe.tag.distance}` see #111

My biggest concern is performance right now.
