### ISSUE TITLE
Provide commit timestamp as property

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#56]
For reproducible maven builds it would be great if the extension can provide the commit timestamp in iso format as a property.

See this description:
https://maven.apache.org/guides/mini/guide-reproducible-builds.html

Then I could use this property as input for project.build.outputTimestamp

**Comment by qoomon** [comment]
Sounds reasonable. I will work on this, or do you like to do a PR

**Comment by qoomon** [comment]
Released new version `4.7.0`
* timestamp properties added
  * `git.commit.timestamp`
  * `git.commit.timestamp.datetime`

**Comment by qoomon** [comment]
please let me know if it suits your needs.

**Comment by reitzmichnicht** [comment]
Works great for the new maven reproducible builds feature. Perhaps you can add this to your documentation:
```
<!-- reproducible builds -->
    <project.build.outputTimestamp>${git.commit.timestamp.datetime}</project.build.outputTimestamp>
```

**Comment by qoomon** [comment]
@reitzmichnicht  oh thats nice
may you can create a PR for that
