### ISSUE TITLE
What about a dirty indicator?

### ISSUE THREAD

**Issue by Puccet** [qoomon/maven-git-versioning-extension#58]
It would be very useful to know if the build was done with a clean or dirty repo, I can't find any info in the documentation about this.

**Comment by qoomon** [comment]
Will add this after my vacation end of december

**Comment by Puccet** [comment]
Great to hear! You just won a true Italian Pizza ;-) let me know if you pass near Genoa.

**Comment by qoomon** [comment]
@Puccet actually that's funny, cause I am on vacation in italy right now :-D near Bolzano

**Comment by qoomon** [comment]
@Puccet do you have an expectation on how the dirty flag indicator should look like.
I think it should be an replacement variable like `${dirtyflag}`.
What should be the default value `${dirtyflag}` what about `-DIRTY`?

**Comment by Puccet** [comment]
I think that would be perfect!

**Comment by Puccet** [comment]
> @Puccet actually that's funny, cause I am on vacation in italy right now :-D near Bolzano

Oh yeah!

**Comment by qoomon** [comment]
Hmm maybe it make more sense to add an option for branch and tag configurations like `allowDirtyState` and throw an exception in case of violation.
branch default would be `true`
tag default would be  `false`

WDYT?

**Comment by qoomon** [comment]
BTW 
What is the main reason you'd like to use this flag for? What kind of workflow?

**Comment by Puccet** [comment]
> Hmm maybe it make more sense to add an option for branch and tag configurations like `allowDirtyState` and throw an exception in case of violation.
> branch default would be `true`
> tag default would be `false`
> 
> WDYT?

Yes absolutely! sorry for the delay but I was out for work purposes and very few spare time

**Comment by Puccet** [comment]
> BTW
> What is the main reason you'd like to use this flag for? What kind of workflow?

There are two scenario:

- release for production
- developing

In release for production, it should not be possible to build if the checkout is dirty, so the exception would be very useful

In developing you should be able to try a dirty build for debugging or testing purposes but the artifact should report this in its name so no one will use it for a different scope, just in case it get out of control and delivered outside the development department.

**Comment by reitzmichnicht** [comment]
In my opinion those release checks should not be part of this extension. I plan to fork the maven-release-plugin to only do those release checks without forcing to have a -SNAPSHOT version in pom.xml

**Comment by qoomon** [comment]
I think we probably should use the maven enforcer plugin to do that.

Michael Düsterhus <notifications@github.com> schrieb am Di., 17. Dez. 2019,
11:45:

**Comment by Puccet** [comment]
> In my opinion those release checks should not be part of this extension. I plan to fork the maven-release-plugin to only do those release checks without forcing to have a -SNAPSHOT version in pom.xml

Yes, but sometime during development you need to do a clean/package not install si the fact that the package name is marked as dirty it's very useful

**Comment by reitzmichnicht** [comment]
Also for your dev case described it makes more sense to fail the build in dirty state in the verify phase, than to have the version changed to dirty and installed to the repo.

**Comment by Puccet** [comment]
That could be another option, yes

**Comment by qoomon** [comment]
I think i agree with @reitzmichnicht

**Comment by qoomon** [comment]
Should we still introduce the dirty flag placeholder? 
should I add this dirty check functionality during verify phase(enable disable by a toggle in the extension config)?

**Comment by Puccet** [comment]
Ok, the best of the two worlds would be if the flag for the verify phase is disable the dirty placeholder is added to keep the real status is always tracked.

**Comment by qoomon** [comment]
hmm sounds complicated to me.
maybe just an option to enforce clean state on non `-SNAPSHOT` versions

**Comment by reitzmichnicht** [comment]
I would suggest to provide just the git.dirty property.
This can than be used like this:
```
<plugin>
  maven-install-plugin
<configuration>
<skip>${git.dirty}</skip>
</configuration>
</plugin>
```

**Comment by qoomon** [comment]
For now I will close this issue and only provide the `${git.dirty flag}` property.
I don't feel comfortable with git.dirty as an optional part of a version, because it will need a lot of effort to make it as configurable as I would like it. For example make the separator for the dirty flag configurable.
I think it's not worth it. 
As @reitzmichnicht mentioned you could use the `${git.dirty}` property to use it in other plugins to ensure repository is in a non dirty state.
