### ISSUE TITLE
Using LATEST version

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#59]
I see in [Maven 3 notes](https://cwiki.apache.org/confluence/x/PIcr#Maven3.xCompatibilityNotes-PluginMetaversionResolution) that `LATEST` and `RELEASE` are removed as metadata version markers. The readme of this extension still recommends usage of them. Is it different when using extension versions as compared to dependency/plugin versions?

If `LATEST` is no longer desirable, what is recommended for targeting this extension?

Thanks!

**Comment by qoomon** [comment]
It is not recommended. Actually it is highly recommend to use a fixed version. I just used this a a placeholder for the latest version so I can not forget to update this example with a new release version.

I will change that, cause obviously it is misleading
