### ISSUE TITLE
Using with non-multi-module parent pom 

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#60]
We are (happily) using your extension but are currently on a very old version (1.2.0). We are upgrading to a newer version but it seems like usage with parent pom has changed slightly.

We have a "parent" pom that is the parent of all the projects in our organization. It has some common settings for `distributionManagement` and build `plugins`. It is not related to any specific project and doesn't have any modules.

In our individual applications we:
* reference the parent pom
* use this extension to set version based on branch or tag name (branch name in development, tag name for releases)

However when updating to version 4.8.0 of this extension I see that parent pom version logic is also present and getting modified by this extension and I am not sure how to handle it.

I have an example repo here: https://github.com/l3ender/maven-demo. Note that I have the parent pom in the same repo for convenience, but in our environment we publish it to our internal repository separately. Running `mvn clean` results in the following, where both current project and parent project version is updated.
```
-> mvn clean -Dgit.branch=abc
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------- maven-git-versioning-extension:4.8.0 -----------------
[INFO] Adjusting project models...
[INFO]
[INFO] --- l3ender:maven-demo @ branch abc ---
[INFO] properties:
[INFO]
[INFO] --- l3ender:maven-demo-parent @ branch abc ---
[INFO] project version: abc-SNAPSHOT
[INFO] properties:
[INFO]
[INFO]
[INFO] -------------------------< l3ender:maven-demo >-------------------------
[INFO] Building maven-demo abc-SNAPSHOT
```

In our scenario we don't want the parent pom version to be modified as it isn't part of this project. Can you please advise on a way to accomplish this or to think about it differently?

**Comment by qoomon** [comment]
I think it is because of this logic https://github.com/qoomon/maven-git-versioning-extension/blob/69a5219916a4642d25cf083f80d5fc6ba68690a9/src/main/java/me/qoomon/maven/gitversioning/MavenUtil.java#L51

**Comment by qoomon** [comment]
I will try to fix that tomorrow.

**Comment by qoomon** [comment]
I could check if parent pom is part of git repo as well. WDYT?

**Comment by l3ender** [comment]
> I could check if parent pom is part of git repo as well. WDYT?

That makes sense to make--if a pom isn't part of the repo, I wouldn't expect the version details to be modified. Though others are perhaps using Maven in more advanced ways and would have different thoughts.

Thanks for the quick response! It is not urgent--take your time.

**Comment by qoomon** [comment]
I've just release version `4.10.1` should work now.
However your example project still does not because the example parent pom.xml is part of the git repository.

**Comment by qoomon** [comment]
Does the new version fulfill your requirements?

**Comment by l3ender** [comment]
Sorry, @qoomon, I haven't had a chance to pull in the updated version to verify. I will tomorrow (Tuesday) or Wednesday and let you know.

I really appreciate your super fast response and great support for the extension!

**Comment by qoomon** [comment]
No hurry.

**Comment by reitzmichnicht** [comment]
I think it's not the right decision to change behavior wether a file is part of a repo or not. The extension shall change the pom.xml and its modules it is invoked with.

**Comment by qoomon** [comment]
My idea was to prevent accidently change files outsize of the repository
(update pom feature) and if a file is not part of the repository it
probably should not versioned by a git version plugin.
WDYT?

Michael Düsterhus <notifications@github.com> schrieb am Di., 17. Dez. 2019,
11:53:

**Comment by reitzmichnicht** [comment]
Looking at the provided demo repo I would expect that the parent-pom.xml is not touched at all by this extension, because maven is executed with pom.xml, so the whole parent chain above pom.xml needs to be ignored independent if they are locally available or not.

**Comment by qoomon** [comment]
@reitzmichnicht I think you are right I think it should be part of the repo otherwise it can't be versioned by git and a child of root pom.
any idea how to check for that?

**Comment by qoomon** [comment]
I think I need to remember and build a project tree myself during processing :-/
however should be possible I think, so far :-D

**Comment by reitzmichnicht** [comment]
I have a related issue that the versioning extension is not adjusting the parent version of modules.

Given the following setup:
updatePom = true

A/pom.xml
with Module B defined
A/B/pom.xml with a parent entry to A including version.

Then the version inside the parent reference to A is not updated.

**Comment by reitzmichnicht** [comment]
As a workaround I use this goal:
versions:update-parent

**Comment by qoomon** [comment]
@reitzmichnicht  oh sound like real bug, may you open another issue for that.

**Comment by qoomon** [comment]
@reitzmichnicht what is your directory wenn you execute the maven command?
Within  `A/` or `A/B/`

**Comment by reitzmichnicht** [comment]
I created new ticket #62

**Comment by qoomon** [comment]
@reitzmichnicht I've added a check to ensure every modified pom is a sub project from execution root see e26d93f6cd4d733d4a33408aa31a0c4f52698b16 (`allProjectDirectories `) will be released with the next version

**Comment by qoomon** [comment]
released within version `4.10.2`

**Comment by qoomon** [comment]
Only projects fulfill all of following conditions will affected by git versionig extension.

* project `pom.xml` needs to be the root-project or a sub-project of root-project
* project `pom.xml` needs to be part of the same repository as the root project

**Comment by l3ender** [comment]
Thank you!
