### ISSUE TITLE
Update of submodules not working

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#62]
I have a related issue that the versioning extension is not adjusting the parent version of modules.

Given the following setup:
updatePom = true

A/pom.xml
with Module B defined
A/B/pom.xml with a parent entry to A including version.

When running maven on A/pom.xml then the version in A/B/pom.xlm inside the parent reference to A is not updated.

**Comment by qoomon** [comment]
Thanks for the report, I will most likely tackle this over the weekend.

**Comment by qoomon** [comment]
@reitzmichnicht may you can provide an example project, cause I can't reproduce your problem. for me it works as expected.

**Comment by reitzmichnicht** [comment]
I'll try to reproduce with the new release and upload a demo project tomorrow.

**Comment by reitzmichnicht** [comment]
Ok the update of submodules works now again.
