### ISSUE TITLE
versions from 4.5.1 to 4.10.2 not build by maven-3.3.9

### ISSUE THREAD

**Issue by dartilla** [qoomon/maven-git-versioning-extension#67]
I have build exception with maven-git-versioning-extension-4.10.2 by maven-3.3.9.
`Caused by: java.lang.ClassNotFoundException: org.apache.maven.shared.utils.logging.MessageUtils`
Full log attached ([log.log](https://github.com/qoomon/maven-git-versioning-extension/files/4163599/log.log))
4.10.0 works just fine.

**Comment by dartilla** [comment]
Actually I was wrong.
All versions from 4.5.0 also broken.

**Comment by qoomon** [comment]
do you mean building the project it self or using the extension with maven 3.3.9?

**Comment by dartilla** [comment]
I mean using maven-git-versioning-extension with maven-3.3.9.

**Comment by qoomon** [comment]
I will investigate at the weekend.

**Comment by qoomon** [comment]
I found the reason, it's because I use methods from a newer version of `maven-core` dependency with `<scope>provided</scope>`
I'll will release a fix soon.

**Comment by qoomon** [comment]
I fixed it will be released in version 5.0.0

**Comment by qoomon** [comment]
just released version `5.0.0`

**Comment by dartilla** [comment]
I confirm that `java.lang.ClassNotFoundException: org.apache.maven.shared.utils.logging.MessageUtils` is not thrown in 5.0.0.
Closing issue.

**Comment by dartilla** [comment]
Thank you!
