### ISSUE TITLE
"skip - versioning is disabled" repeated a lot in maven logs on WARNING level

### ISSUE THREAD

**Issue by Lajcik** [qoomon/maven-git-versioning-extension#72]
Just a small issue, when disabling the extension with `-Dversioning.disable=true` it prints the following message a lot:

> [WARNING] skip - versioning is disabled

There's screens and screens of this message repeating making it hard to read whatever output was desired from maven.

It would be ideal if this message was printed only once.

**Comment by qoomon** [comment]
Makes totaly sense, I will fix it

**Comment by qoomon** [comment]
Which version do you use? Actually this message is printed as `[INFO]`only and only once. I've fixed that some time ago?

**Comment by qoomon** [comment]
Latest version is `5.1.0`

**Comment by Lajcik** [comment]
My bad. I'm on 4.10.0.
Thanks for the quick response and sorry for not double-checking my version.

**Comment by qoomon** [comment]
you're welcome, no problem
