### ISSUE TITLE
[Feature request] version of ${ref} without slashes for properties

### ISSUE THREAD

**Issue by jgerken** [qoomon/maven-git-versioning-extension#73]
I need to set a property via the extension which needs to include the `${ref}` the value but must not include `/` as it will be used in as an OSGI bundle identifier. When used in versions, the `/` are replaced by `-` automatically. When used in  properties this does not happen. I understand that this behaviour cannot be changed as it will potentially break existing projects. Would it be possible that you add a version of the `${ref}` in which the `/` are also replaced by `-` or an attribute to the `property` tag so that all `/` are replaced by `-` in the final value of the property? Actually, I would prefer the latter solution if possible.

Thanks for considering :)

**Comment by qoomon** [comment]
maybe something like `${ref.slug} `

**Comment by qoomon** [comment]
what about following slug logic
* to lowercase
* replace `[^\w-]` with ``

**Comment by jgerken** [comment]
Sounds good to me :)

**Comment by qoomon** [comment]
I will create a release at this weekend, stay tuned :-)

**Comment by qoomon** [comment]
Just released version `5.3.0`, should be available on maven central in some minutes.

**Comment by jgerken** [comment]
Thanks a lot! Works like a charm :)
