### ISSUE TITLE
Using properties in pattern definition

### ISSUE THREAD

**Issue by MarcinGil** [qoomon/maven-git-versioning-extension#74]
I was trying to use properties defined POM file to configure this extension to use like:

    <tag>
        <pattern>${scm.tag}-<![CDATA[v(?<tagVersion>.+)]]></pattern>
        <versionFormat>${tagVersion}</versionFormat>
    </tag>

But of receive:

[ERROR]     Non-readable POM /home/plinmagi/Projects/redbend/src/broker-activemq/pom.xml: Git Versioning Model Processor: Illegal repetition near index 0
[ERROR]     ${scm.tag}-v(?<tagVersion>.+)

Escaping the `${scm.tag}` does not improve. Does the pattern has to be a literal?

Is it at all possible to use properties in extension configuration?

**Comment by qoomon** [comment]
currently there is no support for placeholders within patterns.
the reason is that this extension basically works before pom.xml is evaluated and therefore has no access to properties from the pom.xml at execution time
