### ISSUE TITLE
5.2.0 changes

### ISSUE THREAD

**Issue by l3ender** [qoomon/maven-git-versioning-extension#75]
I see there is a 5.2.0 version in [Maven](https://mvnrepository.com/artifact/me.qoomon/maven-git-versioning-extension/5.2.0), but I don't see any update in changelog or a Github release. Could you please share what is updated?

Thanks!

**Comment by qoomon** [comment]
oh my bad. I've added following change entry to `README.md`
## 5.2.0
* new version format placeholder `${ref.slug}` alike `${ref}` with all `/` replaced by `-`
* new property `git.ref.slug`  alike `git.ref` with all `/` replaced by `-`
