### ISSUE TITLE
long list of warnings when disabling the extension

### ISSUE THREAD

**Issue by beirtipol** [qoomon/maven-git-versioning-extension#77]
If I use the flag -Dversioning.disable=true I get a ***lot*** of 

`[WARNING] skip - versioning is disabled`

Is there a way to suppress that output?

**Comment by qoomon** [comment]
which version do you use?

**Comment by beirtipol** [comment]
Using 4.10.0

**Comment by beirtipol** [comment]
Ah, just saw there's a later version available with exactly that fix. Can I suggest updating the main README to use the latest version? It's currently set to 4.10.0

**Comment by qoomon** [comment]
good point thx
