### ISSUE TITLE
Compatibility with Tycho pomless builds?

### ISSUE THREAD

**Issue by montex** [qoomon/maven-git-versioning-extension#78]
Hello,

I am using the Tycho Pomless extension, which is used to build Eclipse plugins with Maven. The extension allow re-using dependency information included in plugins' MANIFEST.MF files, thus allowing Maven to run without (or with a reduced number of) pom files. 

I would like to use your plugin in this scenario, but apparently it is not compatible with Tycho. I was wondering if you have any suggestion on things I could try. It is running (apparently) but it stops complaining of missing pom files.

More information on Tycho Pomless builds:
- https://www.vogella.com/tutorials/EclipseTycho/article.html
- https://www.eclipse.org/tycho/

Thanks,
Leonardo.

**Comment by montex** [comment]
Please see an example of the output I get when running Maven: [output.txt](https://github.com/qoomon/maven-git-versioning-extension/files/4929237/output.txt)

**Comment by qoomon** [comment]
I will have a look at this at upcoming weekend.

**Comment by qoomon** [comment]
Can you share a very simple example project?

**Comment by montex** [comment]
The project on which I am trying to use is [this one](https://github.com/montex/TMDL-Framework). I created a "qoomon" branch in which there is just one simple plugin. The main pom.xml is in the _plugins_ folder.

Thanks!

**Comment by qoomon** [comment]
May you try to list git-version-extension first like this 
```xml
<extensions>
  <extension>
    <groupId>me.qoomon</groupId>
    <artifactId>maven-git-versioning-extension</artifactId>
    <version>5.2.0</version>
  </extension>
  <extension>
    <groupId>org.eclipse.tycho.extras</groupId>
    <artifactId>tycho-pomless</artifactId>
    <version>1.7.0</version>
  </extension>
</extensions>

```

**Comment by montex** [comment]
Hello, I had tried already, it still does not work, but I get a different error:

`[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal me.qoomon:maven-git-versioning-extension:5.2.0:git-versioning (git-versioning) on project org.modelspartiti.infrastructure: Git Versioning Pom Replacement Mojo: NullPointerException -> [Help 1]
`

**Comment by qoomon** [comment]
I was able to solve the null pointer exception, however my extension only adjust version from root project pom. This is done by purpose because this extension should never affect parent poms.

May you can explain why the project root is a child of an other project that resides in a child folder?

**Comment by montex** [comment]
Thank you!

Well, to be honest I followed [this tutorial](https://www.vogella.com/tutorials/EclipseTycho/article.html) because I am new to using Maven for Eclipse plugin development. I suspect it is to have the configuration of the release in a plugin-like project, so that it can be imported in the Eclipse workspace together with the rest.

But I was also wondering if this is necessary, and I will try to modify the configuration to just use the root pom.

**Comment by qoomon** [comment]
Hi @montex I've played around with Tycho however I didn't find a way to make it work.
I will keep trying. I think I have to dive into Tycho to understand how it works and interferes with git version extension.

**Comment by montex** [comment]
Hello @qoomon, thank you for the effort!

If you want to check some project that is more consolidated than mine, many [official Eclipse projects](https://git.eclipse.org/c/) use Tycho, for example [CDT](https://git.eclipse.org/c/cdt/org.eclipse.cdt.git/tree/).

**Comment by qoomon** [comment]
You may can try the latest version `6.0.4` again.
