### ISSUE TITLE
Provide commitDistance property

### ISSUE THREAD

**Issue by diroussel** [qoomon/maven-git-versioning-extension#8]
jgitver has a 'useCommitDistance' option.  It would nice to be have a similar depth property in maven-git-versioning-extension to count the number of commits on the branch, and be able to use that in the version.

**Comment by qoomon** [comment]
sounds useful, let me see what I can do.

**Comment by qoomon** [comment]
what commitDistance should represent? Actually what distance do you mean?

**Comment by qoomon** [comment]
I thought about you feature request, so I think it would be possible to build,
however I don't like the idea of mutable versions.
The version would change if another version tag is created before commit that you want to build e.g.

version format: ...-${tagDistance}
Commit1 <-- Tag1   => version: ...-0
Commit2                   => version: ...-1
Commit3                   => version: ...-2

version format: ...-${tagDistance}
Commit1 <-- Tag1   => version: ...-0
Commit2 <-- Tag2  => version: ...-0   <-- Changed Version although same commit
Commit3                   => version: ...-1   <-- Changed Version although same commit

What is the use case for having this feature?
So I would suggest to never use relative versioning.

**Comment by diroussel** [comment]
It's particularly useful for build numbers that are sequential. 

If you publish builds from a continous delivery pipeline and push artifacts into Nexus you need a release version for every build. 

You can use the git hash, but that is not sequential. So builds are unordered. 

You can use a timestamp, they are sequential. But there are hard to compare at a glance because they are long YYYYMMDD-hhmmssSSS

Tags are not usually produced on each build in a continous delivery system. 

But the distance from the first commit on master never changes (if rebate is not allowed). So each build gets unique and sequential number. 

Note that you can get Jenkins to give a sequence number. But if Jenkins is running in a container if gets difficult to maintain that state.

**Comment by qoomon** [comment]
I could implement something like this `git rev-list --first-parent --count HEAD` to determine the commit count on a branch,
however to determine the commit count of a specific commit you need to checkout the whole repository. 
Typically CI Systems will checkout only with a depth of on `git clone --depth 1 $repo`, this would lead to wrong calculation of commit count.

**Comment by qoomon** [comment]
what do you think?
