### ISSUE TITLE
snapshot version when git.dirty=true

### ISSUE THREAD

**Issue by erik-telesoftas** [qoomon/maven-git-versioning-extension#80]
There is useful property `git.dirty` set by extension.
Is it possible to use it to generate SNAPSHOT versions? Currently examples are based purely on patter matching.

Probably re-iterates https://github.com/qoomon/maven-git-versioning-extension/issues/58

**Comment by qoomon** [comment]
no currently there is no way.

**Comment by qoomon** [comment]
I think that's a nice feature though, should be easy to implement. I would add an new option within extension config xml.
Something like `<snapshotVersionIfDirtyGitStatus>true</snapshotVersionIfDirtyGitStatus>`. Any better suggestion for option name? :-)

This option would add `-SNAPSHOT` identifier, if not present already.

WDYT?

**Comment by qoomon** [comment]
I chose an other solution, I just added a new placeholder `${dirty.snapshot}` that will resolve to `-SNAPSHOT` in case of a dirty repo state, e.g. you are in a detached state let say you've checked out a tag and you configured a `<versionFormat>${tag}${dirty.snapshot}</versionFormat>` the resolved version would be something like `1.0.0-SNAPSHOT`. Available in version `6.1.0`
