### ISSUE TITLE
support for "git submodule"

### ISSUE THREAD

**Issue by thomschke** [qoomon/maven-git-versioning-extension#82]
If you run the extension inside a `git submodule` [(see)](https://git-scm.com/book/de/v2/Git-Tools-Submodule)
then you have to load the git repo for the submodule (instead the git root repo)

https://github.com/qoomon/maven-git-versioning-extension/blob/95c7437fd747c5f1b615279e3910692f724d0b46/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L402-L404

**Comment by qoomon** [comment]
May describe current behavior and expected behavior cause I think `new FileRepositoryBuilder().findGitDir(baseDirectory).getGitDir();` return the first enclosing repository.
If you execute maven from within that submodule it should find the right repo.

**Comment by thomschke** [comment]
- create a git submodule in your project by calling `git submodule add <url> <path>` 
- now go inside this submodule, the git status will change completely

that's why this mvn git extension has to generate the `project.version` based on each pom model (instead of the root model)

see PR #83

**Comment by thomschke** [comment]
> May describe current behavior and expected behavior cause I think `new FileRepositoryBuilder().findGitDir(baseDirectory).getGitDir();` return the first enclosing repository.
> If you execute maven from within that submodule it should find the right repo.

https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/abae657d4c871bb08dd2cbf8828d7bf02b6f4743/core/src/main/java/pl/project13/core/JGitProvider.java#L316-L324
