### ISSUE TITLE
Plugins using parent pom's location is causing errors

### ISSUE THREAD

**Issue by cemo** [qoomon/maven-git-versioning-extension#88]
I hit an interesting problem I would like to share. It takes me some times to figure out but at least I found cause.

Plugins such as Checkstyle are using parent's directories to locate configurations like this:

https://github.com/paul-hammant/maven-plugins/blob/a03f27ae0b4d25808ef6dc25aa018d581c44fb79/maven-checkstyle-plugin/src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java#L857-L893

Since versioning plugin is creating another pom which is locating under target directory, it is causing to not locate checkstyle configuration files. I opened this issue to have a record for others. I will come up with some alternative solutions for my case and share here.

**Comment by qoomon** [comment]
Thanks for reporting. Maybe we need to generate the git versioned pom file next to the original one instead of within the target directory. I think the [maven flatten plugin](https://www.mojohaus.org/flatten-maven-plugin/) does it the same way, maybe for this very reason.

**Comment by cemo** [comment]
Yes, then ignoring them in git seems not bad.

**Comment by cemo** [comment]
For those who needs to solve this problem for checkstyle case: package checkstyle config file in a jar then use it. This solves the problem. 

I will remain this issue as open since others can hit another variant of this problem.

**Comment by qoomon** [comment]
this issue should be fixed in next release version `6.0.0`

**Comment by qoomon** [comment]
Just released with version `6.0.1`. Be aware of breaking changes see [CHANGELOG.md](https://github.com/qoomon/maven-git-versioning-extension/blob/master/CHANGELOG.md)
