### ISSUE TITLE
Support for Calendar Versioning

### ISSUE THREAD

**Issue by TomasKroth-TomTom** [qoomon/maven-git-versioning-extension#92]
Would be great if Calendar versioning was supported by the tool. Since the tool already supports usage of commit timestamps this could be easy to achieve by providing a format parameter to `GitVersioningModelProcessor.toTimestampDateTime().`

Something along the lines of:

```
private static String toTimestampDateTime(long timestamp, String pattern) {
        if (timestamp == 0) {
            return "0000-00-00T00:00:00Z";
        }

        return DateTimeFormatter.ofPattern(pattern).ISO_DATE_TIME
                .withZone(ZoneOffset.UTC)
                .format(Instant.ofEpochSecond(timestamp));
 }
 
 //Usage example:
 virtualProjectModel.addProperty("git.commit.timestamp.datetime.year", toTimestampDateTime(gitVersionDetails.getCommitTimestamp(), "yy"))  
  
```

Desirable values would be:

- Year (20, 21, 19)
- Full Year (2020, 2021)
- Month (01..12)
- Day (01..31)

Other possibilities could be derived from: https://calver.org/

**Comment by qoomon** [comment]
Just released with version `6.0.1`. Be aware of breaking changes see [CHANGELOG.md](https://github.com/qoomon/maven-git-versioning-extension/blob/master/CHANGELOG.md)
