### ISSUE TITLE
Standard Maven plugins don't always have a groupId and this causes a NPE

### ISSUE THREAD

**Issue by CyberSliver** [qoomon/maven-git-versioning-extension#93]
The GitVersioningModelProcessor at line 793 assumes a groupId is present for each plugin definition, but this is not always required for the standard Maven plugins since Maven can identify them automatically (org.apache.maven.plugins is assumed).

In the latest release (6.0.2) this will cause a NullPointerException and prevent any Maven processing.

**Comment by qoomon** [comment]
hi @CyberSliver  thanks for reporting, I will fix it right now.

**Comment by qoomon** [comment]
@CyberSliver do you know if this only applies to plugins or does it apply to dependencies as well?

**Comment by qoomon** [comment]
fixed within new release `6.0.3`
