### ISSUE TITLE
Replaces unrelated properties

### ISSUE THREAD

**Issue by tweise** [qoomon/maven-git-versioning-extension#94]
The latest version `6.0.2` replaces properties that are unrelated to the versioning setup. 

In the following example: 
```
  <properties>
    <shade-phase>none</shade-phase>
  </properties>

  <profiles>
    <profile>
      <id>skip-shading-for-pom-only</id>
      <activation>
        <file>
          <exists>src</exists>
        </file>
      </activation>
      <properties>
        <shade-phase>package</shade-phase>
      </properties>
    </profile>
  </profiles>
```

the property value of `none` outside the profile will be replaced with value `package` from within the profile.

**Comment by qoomon** [comment]
thanks again give some minutes

**Comment by qoomon** [comment]
okay I found the root cause

**Comment by qoomon** [comment]
A little of topic however I am struggling if it make sense at all to replace properties within profiles based on git ref. WDYT?

**Comment by tweise** [comment]
I can't think of a use case right now. If it is complicated, maybe just document the restriction and see if anyone needs it in the future?

**Comment by qoomon** [comment]
should be fixed in version `6.0.4`

**Comment by tweise** [comment]
Thanks, I just tried `6.0.4` but the basic version replacement does not appear to work:

`mvn --non-recursive exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' -q -Dversioning.disable=false`

**Comment by tweise** [comment]
Same command produces expected output with `6.0.2`

**Comment by qoomon** [comment]
strange I can not reproduce your finding. Could you give some more details. like pom version, extension configuration and expected version ?

**Comment by tweise** [comment]
It could be that the dependency just hasn't propagated yet (fails silently):
```
[WARNING] The POM for me.qoomon:maven-git-versioning-extension:jar:6.0.4 is missing, no dependency information available
```

**Comment by qoomon** [comment]
Ah yes that is a strange behaviour of maven I came across as well. Version `6.0.4` should become available during the next hours, sometime it need som extra time to propagate to maven central.

**Comment by qoomon** [comment]
seems to be available now, see https://repo1.maven.org/maven2/me/qoomon/maven-git-versioning-extension/6.0.4/

**Comment by tweise** [comment]
Yes, all good now.
