### ISSUE TITLE
feature : support Jenkins pipeline in Kubernetes

### ISSUE THREAD

**Issue by survivant** [qoomon/maven-git-versioning-extension#95]
could it be possible to add a section in the guide : How to add that to our project in Jenkins pipeline ?

I'm using jenkins in Kubernetes. We could use a maven-agent, but don't know how to package the extension in it, or maybe use a global library and call it from our pipeline.

I would like to call that script to update my pom.xml version when I receive a webhook about a new branch was created. Like that I'll be sure that all my branches doesn't have the same artifact version

**Comment by qoomon** [comment]
hi @survivant , I think there are several possibilities to achieve what you want.

I would recommend to just use the virtual (default) version update, means the pom.xml stays untouched, so you will never facing any merge conflicts.
* just setup maven extension like it is explained in the [README.md](https://github.com/qoomon/maven-git-versioning-extension#install)
  *  create a `.mvn` folder in the root project directory, create the `extension.xml` and setup config xml, then you don't need to setup anything in jenkins except export `VERSIONING_GIT_BRANCH` and `VERSIONING_GIT_TAG ` environment variable accordingly to current git situation before you execute maven commands. 

depending on your jenkins git plugins or available environment variables it could look like

```shell
if [[ "$GIT_BRANCH" = origin/tags/* ]]; then
    export VERSIONING_GIT_TAG=${GIT_BRANCH#origin/tags/};
else 
    export VERSIONING_GIT_BRANCH=${GIT_BRANCH#origin/};
fi

mvn verify
```

or like this if you use scripted pipelines

```shell
env.VERSIONING_GIT_TAG = env.TAG_NAME
env.VERSIONING_GIT_BRANCH = env.BRANCH_NAME

mvn verify
```
  
However if you like to update the pom.xml you can make use the `<updatePom>true</updatePom>` option.

Does it help?

**Comment by survivant** [comment]
But this extension need to be install in maven folder?



Le mar. 2 mars 2021 17 h 44, Bengt Brodersen <notifications@github.com> a
écrit :

**Comment by qoomon** [comment]
you don't need to install it. It behave like an normal maven plugin or dependency. It is just defined within the project itself.
`<projectDir>/.mvn/extension.xml` there you define all maven core extension this project should use. 
```xml
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 https://maven.apache.org/xsd/core-extensions-1.0.0.xsd">

    <extension>
        <groupId>me.qoomon</groupId>
        <artifactId>maven-git-versioning-extension</artifactId>
        <version>5.2.0</version>
    </extension>

</extensions>
```

**Comment by qoomon** [comment]
Do you need any further support?

**Comment by survivant** [comment]
@qoomon sorry.  I didn't had time to play with it since.  but I think it will do the job.  At first, I though that I had to install it into maven folder instead of the root project .mvn   

I think it will works fine.
