### ISSUE TITLE
Problem when using two dependencies with same groupId and ArtifactId

### ISSUE THREAD

**Issue by Bimeche** [qoomon/maven-git-versioning-extension#96]
There is a problem when using two dependencies that have the same groupId:ArtifactId pair.
In our project, we use something like this :
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>ExampleArtifact</artifactId>
            <version>1.0.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>ExampleArtifact</artifactId>
            <version>1.0.0</version>
            <classifier>license</classifier>
            <type>zip</type>
        </dependency>
        
So the only differences are the type and classifier, which are not "enough" for the plugin to differentiate them, and when i clean install my project, it gives a "Duplicate key 1.0.0" error.
I proposed a fix in a PR #97

**Comment by qoomon** [comment]
fixed in version `6.2.1`

**Comment by qoomon** [comment]
may you confirm that its working now? recent version is `6.3.0`

**Comment by vboulaye** [comment]
Hi,

I had exactly the same issue in 6.2.0, upgrading to 6.3.0 fixed it.
(you should maybe upgrade the version in the readme to 6.3.0, I used the 6.2.0 because I copied the example!)

Thanks

**Comment by qoomon** [comment]
@vboulaye glad to hear that and thx for the hint I will fix it.
